# -*- coding: utf-8 -*-
"""Homework2_1945581.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UU727dG0ch-fH92Lj19KkQ3jdATbDt4Q
"""

# Import necessary libraries for web scraping and data manipulation
import requests
import bs4
from bs4 import BeautifulSoup
import re

# Set the URL of a specific product page on the website
url = 'https://americanmadestore.us/products/amish-wedding-apple-butter-32oz?_pos=1&_sid=6ebdb3865&_ss=r'
# Custom headers to mimic a browser and avoid getting blocked by the website
headers = {'User-Agent': 'frank/1.0'}
# Send a GET request to the URL
p = requests.get(url, headers=headers)
# Check the status code of the response (200 means OK)
p.status_code

# Parse the HTML content of the page using lxml parser
page = BeautifulSoup(p.content, 'lxml')

# Extract the name of the product
title = page.find('div', class_='title').text.replace('\n', '')
title

# Extract the description of the product (only first 100 characters)
description = page.find('div', class_='rte').text.strip().replace('\n', '').replace('\xa0','')[:100]
description

# Extract the price of the product
price = float(page.find('div', class_='price').text.strip().replace('$',''))
price

# Check if the product is weightable
weightable = 'oz.' in title
weightable

# Define a function to scrape details from a product page
def scrape_product_details(url):
  headers = {'User-Agent': 'frank/1.0'}
  p = requests.get(url, headers=headers)
  page = BeautifulSoup(p.content, 'lxml')

  title = page.find('div', class_='title').text.replace('\n', '')
  description = page.find('div', class_='rte').text.strip().replace('\n', '').replace('\xa0','')[:100]
  price = float(page.find('div', class_='price').text.strip().replace('$',''))
  weightable = 'oz' in title

  return title, description, price, weightable

# Test if the function works
scrape_product_details(url)

import pandas as pd

# Now the URL for the search results page for "apple"
search_url = 'https://americanmadestore.us/search?type=product&q=apple'
p = requests.get(search_url, headers = headers)
page = BeautifulSoup(p.content, 'lxml')
# Find all product cards on the page by targeting their container
ads_tot = page.find_all('div', class_='main_box')
output=[]
# Loop through each product card
for ad in ads_tot:
  ad_url_fin = ad.a['href']
  ad_url = "https://americanmadestore.us"+ad_url_fin
  output.append(scrape_product_details(ad_url))
# Convert the results list into a pandas DataFrame
data = pd.DataFrame(output, columns= ['Title','Description','Price','Weightable'])
data

# Define a function to filter the DataFrame by price
def filter_price(price):
  data_filtr = data
  data_filtr = data_filtr[data_filtr['Price']<price]
  data_filtr.to_excel(f"Data_filtred_{price}.xlsx")
  return data_filtr

filter_price(8)