# -*- coding: utf-8 -*-
"""Enrichment_INAIL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-sGKpatrQHo3aQ2hVDwE_IAkmavuBf24
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q scikit-learn networkx sentence-transformers matplotlib
# utile per i modelli recenti
!pip install -U transformers huggingface_hub

!pip install -U sentence-transformers git+https://github.com/huggingface/transformers@v4.56.0-Embedding-Gemma-preview

# SETUP

import json
import re
import time
import logging
import subprocess
import traceback
import numpy as np
import os
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple, Set
from datetime import datetime
from collections import Counter, defaultdict

# Import principali
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import AgglomerativeClustering
import networkx as nx
from sentence_transformers import SentenceTransformer
from huggingface_hub import login

# Dopo: import networkx as nx
# AGGIUNGI:
try:
    import matplotlib.pyplot as plt
    PLOT_AVAILABLE = True
except ImportError:
    PLOT_AVAILABLE = False
    print("⚠ Matplotlib non disponibile - installare con: pip install matplotlib")


# CONFIGURAZIONE LOGGING & DRIVE
# Inizializza il logger
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# La parte di mount drive viene gestita nella cella Colab (vedi sezione 2)
try:
    from google.colab import drive
    if not os.path.exists('/content/drive/MyDrive'):
        print("Tentativo di montaggio di Google Drive...")
        # Non forziamo il remount, ma lo chiamiamo per assicurare il mount
        drive.mount('/content/drive', force_remount=False)
    else:
        print("Drive già montato.")
except:
    print("Ambiente non Colab o errore nel montaggio Drive.")

# CONFIGURAZIONE

class Config:
    INAIL_DATA_DIR = Path('/content/drive/MyDrive/INAIL_Thesis_Data')
    JSON_DIR = INAIL_DATA_DIR / 'json'
    ENRICHED_DIR = INAIL_DATA_DIR / 'enriched_json'
    LOG_DIR = INAIL_DATA_DIR / 'logs'
    GRAPH_DIR = INAIL_DATA_DIR / 'graphs'

    # LLM: Llama 3.1 8B
    OLLAMA_MODEL = "llama3.1:8b"
    USE_LLM_SUMMARY = True

    # DATI DOMINIO
    DOCUMENT_CATEGORIES = [
        "Rischio chimico e cancerogeno", "Rischio biologico", "Rischio fisico (rumore, vibrazioni, radiazioni)",
        "Prevenzione incendi ed esplosioni", "Sicurezza macchine e attrezzature", "Edilizia e cantieri",
        "Agricoltura e silvicoltura", "Trasporti e logistica", "Settore sanitario", "DPI e dispositivi di protezione",
        "Formazione e addestramento", "Sorveglianza sanitaria", "Normativa e adempimenti",
        "Valutazione e gestione del rischio", "Infortuni e malattie professionali", "Altro"
    ]
    CATEGORY_TERMS = {
        "Rischio chimico e cancerogeno": ["cancerogeni", "mutageni", "chimici", "sostanze", "agenti chimici", "esposizione", "classificazione", "amianto", "fibre", "polveri minerali"],
        "Rischio biologico": ["biologici", "virus", "batteri", "contaminazione", "agenti biologici"],
        "Rischio fisico (rumore, vibrazioni, radiazioni)": ["rumore", "vibrazioni", "radiazioni", "temperature", "fisici"],
        "Prevenzione incendi ed esplosioni": ["incendi", "esplosioni", "antincendio", "emergenza", "evacuazione"],
        "Sicurezza macchine e attrezzature": ["macchine", "attrezzature", "impianti", "manutenzione", "utilizzo"],
        "Edilizia e cantieri": ["cantieri", "edilizia", "costruzioni", "ponteggi", "scavi", "demolizioni"],
        "Agricoltura e silvicoltura": ["agricoltura", "forestali", "agricoltori", "rurale", "coltivazioni", "potatori"],
        "Trasporti e logistica": ["trasporti", "autotrasporto", "conducenti", "veicoli", "logistica", "alcol", "guida"],
        "Settore sanitario": ["sanitario", "ospedale", "infermieri", "medici", "pazienti", "clinica"],
        "DPI e dispositivi di protezione": ["dpi", "dispositivi", "protezione individuale", "respiratori", "maschere"],
        "Formazione e addestramento": ["formazione", "addestramento", "corsi", "certificazione", "istruzione"],
        "Sorveglianza sanitaria": ["sorveglianza", "sanitaria", "medica", "visite", "controlli", "accertamenti"],
        "Valutazione e gestione del rischio": ["valutazione", "gestione", "analisi", "misurazione", "identificazione"],
        "Infortuni e malattie professionali": ["infortuni", "incidenti", "malattie professionali", "statistiche", "cause"]
    }

    KNOWN_PROFESSIONS = [
        "Operai edili", "Carpentieri", "Muratori", "Ponteggiatori", "Elettricisti", "Idraulici", "Saldatori",
        "Meccanici industriali", "Operatori macchine utensili", "Manutentori", "Agricoltori", "Operatori forestali",
        "Potatori", "Infermieri", "Medici", "OSS", "Tecnici di laboratorio", "Radiologi", "Operatori sanitari",
        "Autisti professionali", "Magazzinieri", "Mulettisti", "Tecnici della prevenzione", "RSPP", "ASPP",
        "HSE Manager", "Coordinatori per la sicurezza", "RLS", "Preposti alla sicurezza", "Chimici", "Biologi",
        "Tecnici di laboratorio chimico", "Lavoratori esposti ad agenti chimici pericolosi",
        "Lavoratori esposti ad agenti cancerogeni o mutageni", "Lavoratori esposti ad agenti biologici",
        "Lavoratori esposti a polveri e fibre minerali", "Lavoratori esposti a rumore e vibrazioni",
        "Lavoratori in ambienti confinati", "Lavoratori in quota", "Addetti antincendio",
        "Lavoratori generici", "Tutti i lavoratori"
    ]
    PROFESSION_BLACKLIST = {"Addetti antincendio", "Lavoratori generici", "Tutti i lavoratori"}
    DOMAIN_TERMS = {
        'cancerogeni', 'mutageni', 'esposizione', 'prevenzione', 'protezione', 'valutazione', 'sorveglianza',
        'sanitaria', 'dispositivi', 'respiratori', 'ventilazione', 'aspirazione', 'manipolazione', 'stoccaggio',
        'etichettatura', 'classificazione', 'schede', 'sicurezza', 'infortuni', 'malattie', 'professionali',
        'rischio', 'pericolo', 'normativa', 'adempimenti', 'obblighi', 'responsabilità', 'formazione',
        'addestramento', 'informazione', 'istruzioni', 'incendi', 'esplosioni', 'emergenza', 'evacuazione',
        'cantieri', 'ponteggi', 'scavi', 'demolizioni', 'macchine', 'attrezzature', 'impianti', 'manutenzione',
        'chimici', 'biologici', 'fisici', 'ergonomici', 'rumore', 'vibrazioni', 'radiazioni', 'temperature',
        'elettrico', 'meccanico', 'caduta', 'schiacciamento', 'amianto', 'silice', 'piombo', 'solventi', 'polveri'
    }
    MIN_TEXT_LENGTH = 100

    # CONFIGURAZIONI EMBEDDING GEMMA
    GEMMA_MODEL_NAME = "google/embeddinggemma-300m"
    USE_EMBEDDING_GEMMA = True

    # PERCORSO DEFINITIVO SU DRIVE DOVE È STATO SALVATO IL MODELLO
    LOCAL_EMBEDDING_MODEL_PATH = Path('/content/drive/MyDrive/INAIL_Thesis_Data_old/EmbeddingGemma_Offline')

    # IMPOSTATO A TRUE PER FORZARE IL CARICAMENTO OFFLINE
    USE_LOCAL_HPC_MODEL = True

    # HuggingFace Token
    HARDCODED_HF_TOKEN = ""  # set HUGGINGFACE_TOKEN in the environment
    HF_TOKEN_ENV = "HUGGINGFACE_TOKEN"

    # Threshold aumentati per maggiore precisione
    PROFESSION_THRESHOLD = 0.55
    CATEGORY_THRESHOLD = 0.30

    @classmethod
    def get_hf_token(cls) -> str:
        # Recupera token HuggingFace, usando il token hardcoded come priorità
        if cls.HARDCODED_HF_TOKEN:
            return cls.HARDCODED_HF_TOKEN
        return os.environ.get(cls.HF_TOKEN_ENV)

    @classmethod
    def login_huggingface(cls):
        # Login automatico su HuggingFace
        token = cls.get_hf_token()
        if token:
            try:
                login(token=token, add_to_git_credential=False)
                return True
            except Exception:
                return False
        return False

    @classmethod
    def setup(cls):
        # Verifica percorsi
        if not cls.INAIL_DATA_DIR.exists():
            logger.error("La cartella principale dei dati non esiste. Controlla il mount di Drive.")
            return False

        if not cls.JSON_DIR.exists():
            logger.error(f"Cartella JSON mancante in {cls.JSON_DIR}")
            return False

        json_files = list(cls.JSON_DIR.glob("*.json"))
        if len(json_files) == 0:
            logger.error("Nessun file JSON trovato.")
            return False

        print(f"✓ Trovati {len(json_files)} file JSON")

        for d in [cls.ENRICHED_DIR, cls.LOG_DIR, cls.GRAPH_DIR]:
            d.mkdir(exist_ok=True, parents=True)

        return True

# EMBEDDING MODEL LOADER

def load_embedding_model(use_gemma: bool = True) -> Optional[SentenceTransformer]:

    # Carica EmbeddingGemma (offline da Drive/HPC, con fallback online/cache).


    # CARICAMENTO OFFLINE/HPC (PRIORITARIO DA DRIVE)
    local_path = Config.LOCAL_EMBEDDING_MODEL_PATH
    if Config.USE_LOCAL_HPC_MODEL and local_path.exists():
        print(f"\n[Embedding Model] Tentativo caricamento OFFLINE forzato da: {local_path}")
        try:
            # SentenceTransformer carica il modello direttamente dalla cartella salvata
            model = SentenceTransformer(str(local_path))
            print(f"✓ Modello EmbeddingGemma locale caricato con successo (HPC ready)")
            print(f"  Device: {model.device}")
            return model
        except Exception as e:
            logger.error(f"✗ Errore caricamento modello locale da Drive: {e}")
            print("  Tentativo di procedere con l'opzione online/cache...")


    # LOGICA ONLINE/CACHE (FALLBACK se il caricamento locale fallisce)
    if use_gemma:
        model_name = Config.GEMMA_MODEL_NAME
        print(f"\n[Embedding Model] Tentativo caricamento {model_name} ONLINE/Cache...")

        if not Config.login_huggingface():
             logger.warning(f"⚠ Login fallito o token non valido. Fallback su BERT.")
             use_gemma = False
        else:
            try:
                # Tenta il caricamento dalla cache o il download con il token
                model = SentenceTransformer(model_name)
                print(f"✓ Modello {model_name} caricato con successo da Internet/Cache")
                print(f"  Device: {model.device}")
                return model
            except Exception as e:
                logger.error(f"✗ Errore caricamento {model_name}: {e}")
                print(f"Assicurati di aver accettato la licenza su Hugging Face.")
                use_gemma = False

    # FALLBACK: BERT Multilingue
    fallback_model = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
    print(f"\n[Embedding Model] Fallback al modello: {fallback_model}")
    model = SentenceTransformer(fallback_model)
    print(f"Fallback model caricato  Device: {model.device}")
    return model

# LAW EXTRACTOR

class LawExtractor:
    PATTERNS = {
        'dlgs': [r'[Dd]\.?\s*[Ll]\.?\s*[Gg]\.?\s*[Ss]?\.?\s*(?:n\.?\s*)?(\d+)\s*[/\-°]\s*(\d{2,4})'],
        'dm': [r'[Dd]\.?\s*[Mm]\.?\s+(?:del\s+)?(\d{1,2})[/\-\s]+(\d{1,2})[/\-\s]+(\d{2,4})'],
        'legge': [r'[Ll]\.?\s*(?:n\.?\s*)?(\d+)\s*[/\-°]\s*(\d{2,4})'],
        'dpr': [r'[Dd]\.?\s*[Pp]\.?\s*[Rr]\.?\s*(?:n\.?\s*)?(\d+)\s*[/\-°]\s*(\d{2,4})'],
        'direttiva_ue': [r'[Dd]irettiva\s+(?:UE\s+)?(\d{4})\s*[/\-]\s*(\d+)'],
    }

    def __init__(self):
        self.compiled_patterns = {}
        for tipo, patterns in self.PATTERNS.items():
            self.compiled_patterns[tipo] = [re.compile(p, re.IGNORECASE) for p in patterns]

    def extract_with_confidence(self, text: str) -> Tuple[List[str], Dict[str, float]]:
        found_laws = []
        law_counts = Counter()

        for tipo, compiled_patterns in self.compiled_patterns.items():
            for pattern in compiled_patterns:
                for match in pattern.finditer(text):
                    normalized = self._normalize_law(tipo, match.groups())
                    if normalized:
                        found_laws.append(normalized)
                        law_counts[normalized] += 1

        unique_laws = list(dict.fromkeys(found_laws))[:20]
        confidence = self._calculate_confidence(unique_laws, law_counts)

        return unique_laws, confidence

    def _normalize_law(self, tipo: str, match: tuple) -> Optional[str]:
        try:
            if tipo == 'dlgs':
                return f"D.Lgs. {match[0]}/{self._normalize_year(match[1])}"
            elif tipo == 'dm' and len(match) == 3:
                return f"D.M. {match[0]}/{match[1]}/{self._normalize_year(match[2])}"
            elif tipo == 'legge':
                return f"Legge n. {match[0]}/{self._normalize_year(match[1])}"
            elif tipo == 'dpr':
                return f"D.P.R. {match[0]}/{self._normalize_year(match[1])}"
            elif tipo == 'direttiva_ue':
                return f"Direttiva UE {match[0]}/{match[1]}"
        except:
            return None

    def _normalize_year(self, year_str: str) -> str:
        year = int(year_str)
        return str(2000 + year if year < 50 else 1900 + year if year < 100 else year)

    def _calculate_confidence(self, laws: List[str], counts: Counter) -> Dict[str, float]:
        if not laws:
            return {'overall': 0.0, 'count': 0.0, 'coverage': 0.0, 'coherence': 0.0}

        count_score = min(1.0, len(laws) / 5.0)
        avg_mentions = np.mean([counts[law] for law in laws])
        coverage_score = min(1.0, avg_mentions / 3.0)

        years = []
        for law in laws:
            match = re.search(r'/(\d{4})', law)
            if match:
                years.append(int(match.group(1)))

        if len(years) > 1:
            year_std = np.std(years)
            coherence_score = max(0.0, 1.0 - year_std / 30.0)
        else:
            coherence_score = 0.7

        overall = 0.4 * count_score + 0.35 * coverage_score + 0.25 * coherence_score

        return {
            'overall': round(overall, 3),
            'count': round(count_score, 3),
            'coverage': round(coverage_score, 3),
            'coherence': round(coherence_score, 3)
        }

# DOMAIN-AWARE TF-IDF + EMBEDRANK

class DomainAwareTFIDFExtractor:
    def __init__(self, embedding_model: SentenceTransformer, domain_terms: Set[str]):
        print("[TF-IDF+EmbedRank] Inizializzazione...")
        self.embedding_model = embedding_model
        self.domain_terms = domain_terms
        self.stopwords = self._load_stopwords()

        # Verifica modello
        # Questa verifica mostrerà "google/embeddinggemma-300m" se il modello è stato caricato correttamente.
        model_name = getattr(embedding_model, 'model_card_data', {}).get('model_id', 'unknown')
        print(f"[TF-IDF+EmbedRank] Modello attivo: {model_name}")
        print("[TF-IDF+EmbedRank] ✓ Pronto")

    def extract_keywords_with_confidence(
        self,
        document_text: str,
        top_n: int = 8,
        save_graph: bool = True,
        graph_path: Optional[Path] = None,
        doc_title: str = "Document"
    ) -> Tuple[List[str], Dict[str, Any], Optional[nx.Graph]]:

        tfidf_keywords = self._extract_tfidf_domain_aware(document_text)

        if not tfidf_keywords:
            return [], {'confidence': {'overall': 0.0}}, None

        embedrank_keywords, G = self._embed_rank(tfidf_keywords, document_text)

        final_keywords = self._combine_and_diversify(
            tfidf_keywords, embedrank_keywords, top_n
        )

        confidence = self._calculate_confidence(
            final_keywords, tfidf_keywords, embedrank_keywords, document_text, G
        )

        if save_graph and G and graph_path:
            embedrank_scores = dict(embedrank_keywords)
            self._save_graph(G, embedrank_scores, graph_path, doc_title)

        metadata = {
            'keywords': final_keywords,
            'tfidf_keywords': [kw for kw, _ in tfidf_keywords[:10]],
            'embedrank_keywords': [kw for kw, _ in embedrank_keywords[:10]],
            'confidence': confidence,
            'method': 'TF-IDF-DomainAware + EmbedRank'
        }

        return final_keywords, metadata, G

    def _extract_tfidf_domain_aware(self, text: str, top_n: int = 30) -> List[Tuple[str, float]]:
        text_clean = self._preprocess(text)

        if len(text_clean) < 50:
            return []

        try:
            vectorizer = TfidfVectorizer(
                max_features=100,
                ngram_range=(1, 3),
                stop_words=list(self.stopwords),
                min_df=1,
                lowercase=True,
                token_pattern=r'(?u)\b[a-zàèéìòù]{5,}\b'
            )

            tfidf_matrix = vectorizer.fit_transform([text_clean])
            feature_names = vectorizer.get_feature_names_out()
            scores = tfidf_matrix.toarray()[0]

            boosted_scores = []
            for i, term in enumerate(feature_names):
                score = scores[i]

                if any(domain_term in term for domain_term in self.domain_terms):
                    score *= 1.5

                boosted_scores.append((term, score))

            boosted_scores.sort(key=lambda x: x[1], reverse=True)

            return boosted_scores[:top_n]

        except:
            return []

    def _embed_rank(self, candidates: List[Tuple[str, float]], document_text: str) -> Tuple[List[Tuple[str, float]], nx.Graph]:

        # Questa logica usa il metodo .encode() che è standard nella libreria SentenceTransformer.
        # Funziona perfettamente con il modello EmbeddingGemma caricato.

        if len(candidates) < 3:
            return candidates, nx.Graph()

        candidate_terms = [term for term, _ in candidates[:30]]

        # EMBEDDINGS - NESSUNA MODIFICA NECESSARIA
        doc_emb = self.embedding_model.encode(
            [document_text[:3000]],
            convert_to_numpy=True,
            show_progress_bar=False,
        )[0]

        term_embs = self.embedding_model.encode(
            candidate_terms,
            convert_to_numpy=True,
            show_progress_bar=False,
        )

        G = nx.Graph()

        for i, term_i in enumerate(candidate_terms):
            doc_sim = float(cosine_similarity([term_embs[i]], [doc_emb])[0][0])
            G.add_node(term_i, doc_similarity=doc_sim)

            for j in range(i + 1, len(candidate_terms)):
                term_sim = float(cosine_similarity([term_embs[i]], [term_embs[j]])[0][0])

                if term_sim > 0.3:
                    G.add_edge(candidate_terms[i], candidate_terms[j], weight=term_sim)

        if len(G.nodes()) == 0:
            return candidates, G

        try:
            pagerank_scores = nx.pagerank(G, alpha=0.85, max_iter=100, weight='weight')

            final_scores = []
            for term in candidate_terms:
                pr = pagerank_scores.get(term, 0)
                doc_sim = G.nodes[term].get('doc_similarity', 0)

                combined = 0.6 * pr + 0.4 * doc_sim
                final_scores.append((term, combined))

            final_scores.sort(key=lambda x: x[1], reverse=True)

            return final_scores, G

        except:
            return candidates, G

    def _combine_and_diversify(
        self,
        tfidf_kw: List[Tuple[str, float]],
        embedrank_kw: List[Tuple[str, float]],
        top_n: int
    ) -> List[str]:

        tfidf_dict = dict(tfidf_kw)
        embedrank_dict = dict(embedrank_kw)

        all_terms = set(tfidf_dict.keys()) | set(embedrank_dict.keys())

        combined_scores = {}
        for term in all_terms:
            tfidf_score = tfidf_dict.get(term, 0)
            embedrank_score = embedrank_dict.get(term, 0)

            max_tfidf = max(tfidf_dict.values()) if tfidf_dict else 1.0
            max_embedrank = max(embedrank_dict.values()) if embedrank_dict else 1.0

            tfidf_norm = tfidf_score / max_tfidf
            embedrank_norm = embedrank_score / max_embedrank

            combined_scores[term] = 0.5 * tfidf_norm + 0.5 * embedrank_norm

        sorted_terms = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)

        selected = []
        term_embeddings = {}

        for term, score in sorted_terms:
            if len(selected) >= top_n:
                break

            if len(selected) == 0:
                selected.append(term)
                # NESSUNA MODIFICA NECESSARIA
                term_embeddings[term] = self.embedding_model.encode([term])[0]
                continue

            # NESSUNA MODIFICA NECESSARIA
            term_emb = self.embedding_model.encode([term])[0]

            max_sim = 0
            for sel_term in selected:
                sim = float(cosine_similarity([term_emb], [term_embeddings[sel_term]])[0][0])
                max_sim = max(max_sim, sim)

            if max_sim < 0.70:
                selected.append(term)
                term_embeddings[term] = term_emb

        return selected

    def _calculate_confidence(
        self,
        final_keywords: List[str],
        tfidf_kw: List[Tuple[str, float]],
        embedrank_kw: List[Tuple[str, float]],
        document_text: str,
        graph: nx.Graph
    ) -> Dict[str, float]:

        if not final_keywords:
            return {
                'overall': 0.0,
                'score_distribution': 0.0,
                'document_coverage': 0.0,
                'term_specificity': 0.0,
                'graph_coherence': 0.0
            }

        tfidf_dict = dict(tfidf_kw)
        selected_scores = [tfidf_dict.get(kw, 0) for kw in final_keywords]

        if len(selected_scores) >= 2:
            score_gap = (selected_scores[0] - selected_scores[-1]) / (selected_scores[0] + 1e-6)
            distribution_score = min(1.0, score_gap * 2)
        else:
            distribution_score = 0.5

        doc_lower = document_text.lower()
        found_count = sum(1 for kw in final_keywords if kw in doc_lower)
        coverage_score = found_count / len(final_keywords)

        avg_length = np.mean([len(kw) for kw in final_keywords])
        length_score = min(1.0, avg_length / 12.0)

        domain_count = sum(1 for kw in final_keywords
                            if any(dt in kw for dt in self.domain_terms))
        domain_score = domain_count / len(final_keywords)

        specificity_score = 0.5 * length_score + 0.5 * domain_score

        if graph and len(graph.nodes()) > 1:
            density = nx.density(graph)
            coherence_score = min(1.0, density * 5)
        else:
            coherence_score = 0.5

        overall = (
            0.20 * distribution_score +
            0.40 * coverage_score +
            0.20 * specificity_score +
            0.20 * coherence_score
        )

        return {
            'overall': round(float(overall), 3),
            'score_distribution': round(float(distribution_score), 3),
            'document_coverage': round(float(coverage_score), 3),
            'term_specificity': round(float(specificity_score), 3),
            'graph_coherence': round(float(coherence_score), 3)
        }

    def _preprocess(self, text: str) -> str:
        text = text.lower()
        text = re.sub(r'[^\w\sàèéìòù]', ' ', text)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()

    def _load_stopwords(self) -> Set[str]:
        return {
            'il', 'lo', 'la', 'i', 'gli', 'le', 'un', 'uno', 'una',
            'dei', 'degli', 'delle', 'della', 'dello', 'nell', 'nella', 'nelle', 'nei',
            'di', 'a', 'da', 'in', 'con', 'su', 'per', 'tra', 'fra', 'nel', 'al', 'ai', 'dal', 'dai',
            'come', 'più', 'anche', 'essere', 'avere', 'fare', 'dire', 'stato', 'stata', 'stati', 'state',
            'questo', 'quello', 'stesso', 'altro', 'molto', 'tutto', 'ogni', 'tale', 'quale',
            'quando', 'dove', 'che', 'chi', 'cui', 'cosa', 'quanto', 'anni', 'anno',
            'presente', 'seguente', 'generale', 'gruppo', 'parte', 'caso', 'modo', 'tutti', 'altre', 'altri', 'altra', 'prima', 'dopo',
            'dell', 'degli', 'deve', 'devono', 'può', 'possono', 'viene', 'vengono', 'fatto', 'fatta', 'dovr', 'dovrà', 'dovranno', 'potr', 'potrà', 'potranno',
            'verr', 'verrà', 'verranno', 'andr', 'andrà', 'andranno',
            'sar', 'sarà', 'saranno', 'avr', 'avrà', 'avranno',
            'effettuare', 'effettuato', 'effettuata', 'effettuati',
            'procedere', 'eseguire', 'realizzare', 'adottare',
            'considerare', 'previsto', 'prevista', 'previsti', 'previste',
            'indicato', 'indicata', 'indicati', 'indicate',  'richiesto', 'richiesti', 'richieste',
            'relativo', 'relativa', 'relativi', 'relative',
            'necessario', 'necessaria', 'necessari', 'necessarie',
            'eventuale', 'eventuali', 'possibile', 'possibili'
        }

    def _save_graph(self, G: nx.Graph, scores: Dict[str, float],
                    output_path: Path, doc_title: str):
        """Salva grafo EmbedRank con layout ottimizzato e leggibile"""
        if not PLOT_AVAILABLE or len(G.nodes()) == 0:
            return

        try:
            # Prendi solo i top 15 nodi più rilevanti (invece di 25)
            top_nodes = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:15]
            top_node_names = [node for node, _ in top_nodes]
            G_sub = G.subgraph(top_node_names)

            if len(G_sub.nodes()) == 0:
                return

            # Layout migliorato con più spazio
            pos = nx.spring_layout(G_sub, k=1.5, iterations=100, seed=42)

            # Figura più grande
            plt.figure(figsize=(16, 12))

            # Calcola dimensioni e colori
            max_score = max(scores.values())
            node_sizes = [min(scores.get(node, 0) / max_score * 8000, 8000) for node in G_sub.nodes()]
            node_colors = [scores.get(node, 0) for node in G_sub.nodes()]

            # Disegna nodi
            nx.draw_networkx_nodes(
                G_sub, pos,
                node_size=node_sizes,
                node_color=node_colors,
                cmap=plt.cm.YlOrRd,  # Colori più contrastati
                alpha=0.85,
                edgecolors='darkblue',
                linewidths=2.0
            )

            # Disegna solo edges più forti (similarity > 0.5)
            strong_edges = [(u, v) for u, v, d in G_sub.edges(data=True)
                           if d.get('weight', 0) > 0.5]
            nx.draw_networkx_edges(
                G_sub, pos,
                edgelist=strong_edges,
                alpha=0.3,
                width=1.5,
                edge_color='gray'
            )

            # Labels con sfondo bianco per leggibilità
            labels = {node: node for node in G_sub.nodes()}
            for node, (x, y) in pos.items():
                plt.text(
                    x, y,
                    labels[node],
                    fontsize=10,
                    fontweight='bold',
                    ha='center',
                    va='center',
                    bbox=dict(boxstyle='round,pad=0.3', facecolor='white',
                             edgecolor='darkblue', alpha=0.8)
                )

            # Titolo
            plt.title(f"Keyword Similarity Network: {doc_title[:50]}",
                     fontsize=14, fontweight='bold', pad=20)
            plt.axis('off')
            plt.tight_layout()

            # Salva con nome unico
            safe_title = re.sub(r'[^\w\-_]', '_', doc_title[:40])
            graph_file = output_path.parent / f"{safe_title}.png"
            plt.savefig(graph_file, dpi=150, bbox_inches='tight', facecolor='white')
            plt.close()

            print(f"  [Graph] ✓ Saved: {graph_file.name}")

        except Exception as e:
            print(f"  [Graph] Error: {e}")
            plt.close()

# GENERIC THEME EXTRACTOR

class GenericThemeExtractor:
    def __init__(self, embedding_model: SentenceTransformer):
        self.embedding_model = embedding_model

    def extract_themes(
        self,
        keywords: List[str],
        laws: List[str],
        document_text: str
    ) -> List[str]:

        if len(keywords) < 3:
            themes = [kw.capitalize() for kw in keywords[:3]]
            if laws:
                themes.append("Normativa")
            return themes

        # NESSUNA MODIFICA NECESSARIA: .encode() è corretto per SentenceTransformer
        embeddings = self.embedding_model.encode(keywords)
        n_clusters = min(4, max(2, len(keywords) // 3))

        try:
            clustering = AgglomerativeClustering(
                n_clusters=n_clusters,
                metric='cosine',
                linkage='average'
            )
            labels = clustering.fit_predict(embeddings)
        except:
            return [kw.capitalize() for kw in keywords[:4]]

        themes = []
        clusters = defaultdict(list)
        for i, label in enumerate(labels):
            clusters[label].append(keywords[i])

        for cluster_kw in clusters.values():
            if len(cluster_kw) == 1:
                themes.append(cluster_kw[0].capitalize())
            elif len(cluster_kw) == 2:
                themes.append(f"{cluster_kw[0].capitalize()} e {cluster_kw[1]}")
            else:
                # NESSUNA MODIFICA NECESSARIA: .encode() è corretto per SentenceTransformer
                cluster_embs = self.embedding_model.encode(cluster_kw)
                centroid = np.mean(cluster_embs, axis=0)

                distances = [
                    (kw, float(cosine_similarity([emb], [centroid])[0][0]))
                    for kw, emb in zip(cluster_kw, cluster_embs)
                ]
                distances.sort(key=lambda x: x[1], reverse=True)

                top2 = distances[:2]
                themes.append(f"{top2[0][0].capitalize()} e {top2[1][0]}")

        if laws and len(laws) >= 2:
            if not any("normativ" in t.lower() for t in themes):
                themes.append("Normativa")

        return themes[:4]

# ENHANCED CATEGORY CLASSIFIER CON DOMAIN TERMS

class DomainAwareCategoryClassifier:

    def __init__(self, embedding_model: SentenceTransformer, valid_categories: List[str], category_terms: Dict[str, List[str]]):
        self.embedding_model = embedding_model
        self.valid_categories = valid_categories
        self.category_terms = category_terms
        # NESSUNA MODIFICA NECESSARIA: .encode() è corretto per SentenceTransformer
        self.category_embeddings = embedding_model.encode(valid_categories)

    def classify(self, keywords: List[str], themes: List[str], laws: List[str]) -> str:

        all_text = ' '.join(keywords + themes).lower()

        # LIVELLO 1: Scoring basato su domain terms specifici
        domain_scores = {}
        for category, terms in self.category_terms.items():
            matches = sum(1 for term in terms if term in all_text)
            domain_scores[category] = matches / max(len(terms), 1)

        # Aggiungi score per keyword overlap generico
        for category in self.valid_categories:
            if category not in domain_scores:
                cat_words = set(category.lower().split())
                text_words = set(all_text.split())
                overlap = len(cat_words & text_words)
                domain_scores[category] = overlap / max(len(cat_words), 1)

        # PENALIZZA "Normativa" se ci sono categorie più specifiche con score > 0
        if "Normativa e adempimenti" in domain_scores:
            specific_categories = [cat for cat in domain_scores.keys() if cat != "Normativa e adempimenti"]
            max_specific_score = max([domain_scores[cat] for cat in specific_categories], default=0)

            if max_specific_score > 0.15:
                domain_scores["Normativa e adempimenti"] *= 0.3

        # Prendi top 5
        top_candidates = sorted(domain_scores.items(), key=lambda x: x[1], reverse=True)[:5]

        # LIVELLO 2: Semantic similarity su top candidates
        description = f"""Keywords: {', '.join(keywords[:10])}.
Temi: {', '.join(themes[:3])}.
Leggi: {', '.join(laws[:3]) if laws else 'Generiche'}."""

        # NESSUNA MODIFICA NECESSARIA: .encode() è corretto per SentenceTransformer
        desc_emb = self.embedding_model.encode([description])

        best_category = None
        best_score = 0

        for category, domain_score in top_candidates:
            cat_idx = self.valid_categories.index(category)
            sem_score = float(cosine_similarity(desc_emb, [self.category_embeddings[cat_idx]])[0][0])

            # Combina: 70% domain terms + 30% semantic
            combined_score = 0.7 * domain_score + 0.3 * sem_score

            if combined_score > best_score:
                best_score = combined_score
                best_category = category

        # Fallback a "Altro" se score troppo basso
        if best_score < Config.CATEGORY_THRESHOLD:
            return "Altro"

        return best_category

# IMPROVED PROFESSION EXTRACTOR (CON BLACKLIST)

class ImprovedProfessionExtractor:

    def __init__(self, embedding_model: SentenceTransformer, known_professions: List[str], blacklist: Set[str]):
        self.embedding_model = embedding_model
        self.known_professions = known_professions
        self.blacklist = blacklist

        print("[Professions] Pre-computing embeddings...")
        # NESSUNA MODIFICA NECESSARIA: .encode() è corretto per SentenceTransformer
        self.profession_embeddings = embedding_model.encode(known_professions)
        print("[Professions] ✓ Pronto")

    def extract_professions(
        self,
        document_text: str,
        keywords: List[str],
        themes: List[str],
        category: str,
        top_k: int = 3,
        threshold: float = 0.55
    ) -> List[str]:

        doc_desc = f"""Settore: {category}.
Parole chiave: {', '.join(keywords[:8])}.
Temi: {', '.join(themes[:3])}.
Contenuto: {document_text[:1500]}"""

        # NESSUNA MODIFICA NECESSARIA: .encode() è corretto per SentenceTransformer
        doc_emb = self.embedding_model.encode([doc_desc])
        similarities = cosine_similarity(doc_emb, self.profession_embeddings)[0]

        ranked = sorted(
            zip(self.known_professions, similarities),
            key=lambda x: x[1],
            reverse=True
        )

        # Filtra blacklist e applica threshold
        selected = []
        for prof, score in ranked:
            if prof in self.blacklist:
                continue
            if score >= threshold:
                selected.append(prof)
            if len(selected) >= top_k:
                break

        # Fallback: se nessuna sopra threshold, prendi migliore NON in blacklist
        if not selected:
            for prof, score in ranked:
                if prof not in self.blacklist and score > 0.40:
                    selected = [prof]
                    break

        return selected

# SUMMARY GENERATOR

class OllamaClient:
    # Client per interazione con LLM esterno (Ollama)
    def __init__(self, model: str = "llama3.1:8b"):
        self.model = model
        self.base_url = "http://localhost:11434"

    def generate(self, prompt: str, max_tokens: int = 150) -> Optional[str]:
        try:
            # Import requests è necessario. Assunto che sia installato nell'ambiente.
            response = requests.post(
                f"{self.base_url}/api/generate",
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "temperature": 0.1,
                    "max_tokens": max_tokens
                },
                timeout=120
            )
            return response.json()['response'].strip() if response.status_code == 200 else None
        except Exception as e:
            # Fallback in caso di errore di connessione o LLM non disponibile
            return None


class ReliableSummaryGenerator:

    def __init__(self, llm_client: Optional[OllamaClient], embedding_model: SentenceTransformer, use_llm: bool = False):
        self.llm = llm_client
        self.embedding_model = embedding_model
        self.use_llm = use_llm

    def generate_with_confidence(
        self,
        document_text: str,
        keywords: List[str],
        laws: List[str],
        category: str,
        themes: List[str]
    ) -> Tuple[str, Dict[str, float]]:

        if not self.use_llm or not self.llm:
            summary = self._create_structured_summary(keywords, laws, category, themes, document_text)
        else:
            # Prova LLM
            prompt = self._create_prompt(document_text, keywords, laws, category, themes)
            llm_summary = self.llm.generate(prompt, max_tokens=120)

            if llm_summary and len(llm_summary.split()) >= 15 and len(llm_summary.split()) <= 60:
                summary = self._clean_summary(llm_summary)

                if self._has_obvious_errors(summary):
                    summary = self._create_structured_summary(keywords, laws, category, themes, document_text)
            else:
                summary = self._create_structured_summary(keywords, laws, category, themes, document_text)

        confidence = self._calculate_confidence(summary, document_text, keywords, laws)

        return summary, confidence

    def _create_prompt(self, text: str, keywords: List[str], laws: List[str], category: str, themes: List[str]) -> str:
        return f"""Scrivi UNA sintesi tecnica di MASSIMO 50 parole per questo documento INAIL.

SETTORE: {category}
TEMI: {', '.join(themes[:3])}
KEYWORDS (usane almeno 4): {', '.join(keywords[:6])}
NORMATIVE: {', '.join(laws[:2]) if laws else 'Non specificate'}

TESTO:
{text[:2500]}

REGOLE:
- Max 50 parole
- Usa almeno 4 keywords
- Cita normative con nomenclatura esatta
- Linguaggio tecnico INAIL
- NO "Il documento...", scrivi direttamente i contenuti

Sintesi:"""

    def _create_structured_summary(
        self,
        keywords: List[str],
        laws: List[str],
        category: str,
        themes: List[str],
        document_text: str
    ) -> str:

        top_keywords = keywords[:min(4, len(keywords))]

        if themes and len(themes) > 0:
            main_theme = themes[0].lower()
            intro = f"Documento tecnico che tratta {main_theme}"
        else:
            intro = f"Documento nel settore {category.lower()}"

        if len(top_keywords) >= 3:
            kw_part = f"con focus su {top_keywords[0]}, {top_keywords[1]} e {top_keywords[2]}"
        elif len(top_keywords) == 2:
            kw_part = f"con focus su {top_keywords[0]} e {top_keywords[1]}"
        elif len(top_keywords) == 1:
            kw_part = f"relativo a {top_keywords[0]}"
        else:
            kw_part = ""

        if laws and len(laws) <= 3:
            law_part = f"Riferimenti normativi: {', '.join(laws)}"
        elif laws and len(laws) > 3:
            law_part = f"Principali normative: {laws[0]}, {laws[1]}"
        else:
            law_part = ""

        summary_parts = [intro]
        if kw_part:
            summary_parts.append(kw_part)

        if len(summary_parts) == 2:
            summary = f"{summary_parts[0]} {summary_parts[1]}"
        else:
            summary = summary_parts[0]

        if law_part:
            summary = f"{summary}. {law_part}"

        if not summary.endswith('.'):
            summary += '.'

        summary = summary[0].upper() + summary[1:]

        return summary

    def _clean_summary(self, summary: str) -> str:

        summary = summary.strip()
        summary = re.sub(r'^(Il documento|Questo documento|La presente|Il presente)\s+', '', summary, flags=re.IGNORECASE)
        summary = re.sub(r'\*\*.*?\*\*', '', summary)

        words = summary.split()
        if len(words) > 55:
            summary = ' '.join(words[:52]) + '...'

        return summary

    def _has_obvious_errors(self, text: str) -> bool:

        errors = [
            'invenzione conoscitiva',
            'suggerimento attività',
            'entre ',
            'comprovando',
            'conforme D',
        ]

        text_lower = text.lower()
        for error in errors:
            if error.lower() in text_lower:
                return True

        return False

    def _calculate_confidence(
        self,
        summary: str,
        document_text: str,
        keywords: List[str],
        laws: List[str]
    ) -> Dict[str, float]:

        try:
            # NESSUNA MODIFICA NECESSARIA: .encode() è corretto per SentenceTransformer
            sum_emb = self.embedding_model.encode([summary])[0]
            doc_emb = self.embedding_model.encode([document_text[:4500]])[0]
            grounding = float(cosine_similarity([sum_emb], [doc_emb])[0][0])
        except:
            grounding = 0.5

        summary_lower = summary.lower()
        kw_mentioned = sum(1 for kw in keywords[:8] if kw.lower() in summary_lower)
        kw_coverage = kw_mentioned / min(len(keywords), 8)

        if laws:
            laws_mentioned = 0
            for law in laws[:4]:
                law_parts = re.findall(r'\d+', law)
                if any(part in summary for part in law_parts):
                    laws_mentioned += 1

            factuality = laws_mentioned / min(len(laws), 4)
        else:
            factuality = 0.7

        overall = 0.50 * grounding + 0.35 * kw_coverage + 0.15 * factuality

        return {
            'overall': round(overall, 3),
            'grounding': round(grounding, 3),
            'keyword_coverage': round(kw_coverage, 3),
            'factuality': round(factuality, 3)
        }

# GLOBAL CONFIDENCE CALCULATOR

class GlobalConfidenceCalculator:
    """
    Calcola confidence globale con gestione adattiva per documenti senza leggi.
    """

    def calculate(
        self,
        keyword_confidence: Dict[str, float],
        law_confidence: Dict[str, float],
        summary_confidence: Dict[str, float]
    ) -> Dict[str, Any]:

        kw_score = keyword_confidence.get('overall', 0.0)
        law_score = law_confidence.get('overall', 0.0)
        sum_score = summary_confidence.get('overall', 0.0)

        # LOGICA ADATTIVA: se non ci sono leggi, riduci il peso del componente laws
        num_laws = law_confidence.get('count', 0.0)

        if num_laws == 0 or law_score < 0.15:
            # Documento senza leggi: ridistribuisci i pesi
            overall = 0.60 * kw_score + 0.10 * law_score + 0.30 * sum_score
            adapted = True
            adaptation_reason = "Documento generico/informativo senza normative specifiche"
        else:
            # Documento con leggi: usa pesi standard
            overall = 0.45 * kw_score + 0.30 * law_score + 0.25 * sum_score
            adapted = False
            adaptation_reason = None

        review_reasons = []

        # Soglie ADATTIVE
        if adapted:
            high_threshold = 0.62
            medium_threshold = 0.45
        else:
            high_threshold = 0.68
            medium_threshold = 0.52

        if overall >= high_threshold:
            level = "HIGH"
            needs_review = False
        elif overall >= medium_threshold:
            level = "MEDIUM"
            needs_review = True
            review_reasons.append("Confidence medio: verificare campione")
        else:
            level = "LOW"
            needs_review = True
            review_reasons.append("Confidence basso: revisione manuale richiesta")

        if kw_score < 0.48:
            review_reasons.append(f"Keywords confidence basso ({kw_score:.2f})")

        if not adapted and law_score < 0.43:
            review_reasons.append(f"Laws confidence basso ({law_score:.2f})")

        if sum_score < 0.48:
            review_reasons.append(f"Summary grounding basso ({sum_score:.2f})")

        return {
            'overall_score': round(overall, 3),
            'confidence_level': level,
            'needs_review': needs_review,
            'adapted_scoring': adapted,
            'adaptation_reason': adaptation_reason,
            'components': {
                'keywords': round(kw_score, 3),
                'laws': round(law_score, 3),
                'summary': round(sum_score, 3)
            },
            'detailed_components': {
                'keywords': keyword_confidence,
                'laws': law_confidence,
                'summary': summary_confidence
            },
            'review_reasons': review_reasons
        }

# UTILITY

def extract_full_document_text(document_data: Dict[str, Any]) -> str:
    chunks = []
    abstract = document_data.get('web_metadata', {}).get('abstract', '')
    if abstract:
        chunks.append(f"ABSTRACT:\n{abstract}\n")

    content = document_data.get('document_content', {})
    if content.get('plain_text'):
        chunks.append(content['plain_text'])
    elif content.get('markdown_content'):
        chunks.append(content['markdown_content'])

    return '\n\n'.join(chunks)


def setup_logging(log_dir: Path):
    log_dir.mkdir(exist_ok=True, parents=True)
    log_file = log_dir / f"enrichment_final_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(message)s',
        handlers=[logging.FileHandler(log_file), logging.StreamHandler()]
    )
    return logging.getLogger(__name__), log_file

# DOCUMENT ENRICHMENT

def enrich_document_final(
    document_data: Dict[str, Any],
    law_extractor: LawExtractor,
    keyword_extractor: DomainAwareTFIDFExtractor,
    theme_extractor: GenericThemeExtractor,
    profession_extractor: ImprovedProfessionExtractor,
    summary_generator: ReliableSummaryGenerator,
    category_classifier: DomainAwareCategoryClassifier,
    confidence_calculator: GlobalConfidenceCalculator,
    logger: logging.Logger,
    save_graph: bool = True
) -> Optional[Dict[str, Any]]:

    doc_title = document_data.get('web_metadata', {}).get('title', 'N/A')
    logger.info(f"\n{'='*70}")
    logger.info(f"Processing: {doc_title[:60]}")
    logger.info(f"{'='*70}")

    try:
        full_text = extract_full_document_text(document_data)
        # AGGIUNGI CONTROLLO
        if not full_text or full_text.strip() == "":
            logger.warning("⚠ Testo vuoto o None, skip")
            return None
        logger.info(f"[Text] {len(full_text)} chars")

        if len(full_text) < Config.MIN_TEXT_LENGTH:
            logger.warning("Testo troppo corto, skip")
            return None

        # 1) LEGGI
        laws, law_confidence = law_extractor.extract_with_confidence(full_text)
        logger.info(f"[Laws] {len(laws)} found | Confidence: {law_confidence['overall']:.3f}")

        # 2) KEYWORDS
        graph_path = Config.GRAPH_DIR / "temp.png" if save_graph else None
        keywords, kw_metadata, G = keyword_extractor.extract_keywords_with_confidence(
            full_text, top_n=8, save_graph=save_graph,
            graph_path=graph_path, doc_title=doc_title
        )

        logger.info(f"[Keywords] {len(keywords)} selected | Confidence: {kw_metadata['confidence']['overall']:.3f}")
        for i, kw in enumerate(keywords, 1):
            logger.info(f"  {i}. {kw}")

        # 3) TEMI
        themes = theme_extractor.extract_themes(keywords, laws, full_text)
        logger.info(f"[Themes] {len(themes)} extracted")
        for tema in themes:
            logger.info(f"  • {tema}")

        # 4) CATEGORIA (domain-aware)
        categoria = category_classifier.classify(keywords, themes, laws)
        logger.info(f"[Category] {categoria}")

        # 5) SINTESI (preferisce fallback strutturato)
        sintesi, summary_confidence = summary_generator.generate_with_confidence(
            full_text, keywords, laws, categoria, themes
        )
        logger.info(f"[Summary] Confidence: {summary_confidence['overall']:.3f}")
        logger.info(f"  {sintesi}")

        # 6) PROFESSIONI (con blacklist)
        professioni = profession_extractor.extract_professions(
            full_text, keywords, themes, categoria, top_k=3, threshold=Config.PROFESSION_THRESHOLD
        )
        logger.info(f"[Professions] {len(professioni)} found")
        for prof in professioni:
            logger.info(f"  • {prof}")

        # 7) CONFIDENCE GLOBALE (CON ADATTAMENTO)
        # num_laws = len(laws)
        global_confidence = confidence_calculator.calculate(
            kw_metadata['confidence'],
            law_confidence,
            summary_confidence
        )

        # Log con indicazione dell'adattamento
        logger.info(f"\n[GLOBAL CONFIDENCE]")
        logger.info(f"  Overall: {global_confidence['overall_score']:.3f}")
        logger.info(f"  Level: {global_confidence['confidence_level']}")

        if global_confidence.get('adapted_scoring'):
            logger.info(f"  ⚙ Scoring Adattivo: {global_confidence.get('adaptation_reason')}")

        logger.info(f"  Needs Review: {'YES' if global_confidence['needs_review'] else 'NO'}")

        if global_confidence['review_reasons']:
            logger.info(f"  Reasons:")
            for reason in global_confidence['review_reasons']:
                logger.info(f"    ⚠ {reason}")

        # 8) METADATA
        metadata = {
            'sintesi': sintesi,
            'categoria_principale': categoria,
            'articoli_legge': laws,
            'categorie_professionali': professioni,
            'parole_chiave': keywords,
            'temi_principali': themes,
            'confidence': global_confidence,
            'extraction_details': kw_metadata,
            'extraction_methods': {
                'keywords': 'TF-IDF Domain-Aware + EmbedRank (Bennani-Smires 2018)',
                'themes': 'Semantic Clustering',
                'category': 'Domain-Aware Hierarchical (term mapping + semantic)',
                'laws': 'Regex Pattern Matching + Multi-metric',
                'summary': 'Structured Fallback (deterministic) + optional LLM',
                'professions': 'BERT Semantic + Blacklist Filtering',
                'confidence': 'Multi-component (distribution + coverage + specificity + coherence)'
            },
            'generated_at': datetime.now().isoformat(),
            'version': 'Final_EmbeddingGemma_v4.0_AdaptiveScoring'
        }

        enriched_doc = document_data.copy()
        enriched_doc['semantic_metadata'] = metadata

        logger.info(f"{'='*70}\n")

        return enriched_doc

    except Exception as e:
        logger.error(f"ERROR processing {doc_title}: {e}")
        traceback.print_exc()
        return None

# OLLAMA SETUP

def check_ollama_installed():
    try:
        result = subprocess.run(['which', 'ollama'], capture_output=True, timeout=5)
        return result.returncode == 0
    except:
        return False


def install_ollama():
    if check_ollama_installed():
        print("[Setup] Ollama già installato ✓")
        return True

    print("[Setup] Installing Ollama...")
    try:
        subprocess.run(['bash', '-c', 'curl -fsSL https://ollama.ai/install.sh | sh'],
                       check=True, capture_output=True, timeout=300)
        print("✓ Ollama installed")
        return True
    except Exception as e:
        print(f"✗ Error: {e}")
        return False


def start_ollama():
    print("[Setup] Starting Ollama...")
    try:
        # Check se già running
        result = subprocess.run(['pgrep', '-x', 'ollama'], capture_output=True)
        if result.returncode == 0:
            print("✓ Ollama già running")
            return True

        # Usa Popen per avviare in background
        subprocess.Popen(['ollama', 'serve'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        time.sleep(5) # Give time to start
        print("✓ Server started")
        return True
    except Exception as e:
        print(f"✗ Error starting ollama: {e}")
        return False


def pull_model(model_name: str):
    print(f"[Setup] Checking {model_name}...")
    try:
        # Check se già scaricato
        result = subprocess.run(['ollama', 'list'], capture_output=True, text=True, timeout=10)
        if model_name.split(':')[0] in result.stdout:
            print(f"✓ {model_name} già disponibile")
            return True

        print(f"[Setup] Downloading {model_name}...")
        result = subprocess.run(['ollama', 'pull', model_name],
                                capture_output=True, timeout=600, text=True)
        if result.returncode == 0:
            print(f"✓ {model_name} ready")
            return True
        else:
            print(f"✗ Download failed: {result.stderr}")
            return False
    except Exception as e:
        print(f"✗ Error: {e}")
        return False

# QUICK TEST & BATCH PROCESSING

def quick_test():

   # Versione modificata con EmbeddingGemma
    print("\n" + "="*80)
    print("TEST - FINAL CORRECTED SYSTEM (EmbeddingGemma Edition)")
    print("="*80 + "\n")

    print("[Setup] Verifying paths...")
    if not Config.setup():
        print("\n✗ Setup failed\n")
        return

    logger, log_file = setup_logging(Config.LOG_DIR)
    print("LOG FILE =", logfile)

    # LLM Setup
    llm_client = None
    if Config.USE_LLM_SUMMARY:
        print("\n[Setup] Configuring LLM...")
        if not install_ollama() or not start_ollama():
            print("✗ Ollama setup failed, using fallback summary")
        elif pull_model(Config.OLLAMA_MODEL):
            llm_client = OllamaClient(model=Config.OLLAMA_MODEL)
        else:
            print("✗ Model download failed, using fallback summary")
    else:
        print("\n[Setup] Using structured fallback summary (no LLM)")

    # EMBEDDING MODEL
    print("\n[Setup] Initializing embedding model...")
    embedding_model = load_embedding_model(use_gemma=Config.USE_EMBEDDING_GEMMA)
    print("✓ Embedding model ready\n")

    # Inizializza componenti
    law_extractor = LawExtractor()
    keyword_extractor = DomainAwareTFIDFExtractor(embedding_model, Config.DOMAIN_TERMS)
    theme_extractor = GenericThemeExtractor(embedding_model)
    profession_extractor = ImprovedProfessionExtractor(
        embedding_model,
        Config.KNOWN_PROFESSIONS,
        Config.PROFESSION_BLACKLIST
    )
    summary_generator = ReliableSummaryGenerator(
        llm_client,
        embedding_model,
        Config.USE_LLM_SUMMARY
    )
    category_classifier = DomainAwareCategoryClassifier(
        embedding_model,
        Config.DOCUMENT_CATEGORIES,
        Config.CATEGORY_TERMS
    )
    confidence_calculator = GlobalConfidenceCalculator()

    print("✓ All components ready\n")

    json_files = sorted([f for f in Config.JSON_DIR.glob("*.json")
                         if not f.name.startswith('vector_db')])

    if not json_files:
        print(f"✗ No JSON in {Config.JSON_DIR}")
        return

    print(f"Available: {len(json_files)}\n")
    for i, f in enumerate(json_files[:10], 1):
        print(f"{i}. {f.name[:70]}")

    idx_input = input(f"\nWhich? (1-{min(10, len(json_files))}, default 1): ").strip()
    idx = int(idx_input) - 1 if idx_input.isdigit() else 0
    test_file = json_files[idx] if 0 <= idx < len(json_files) else json_files[0]

    save_graph = input("Save EmbedRank graph? (y/n, default n): ").strip().lower() == 'y'

    with open(test_file, 'r', encoding='utf-8') as f:
        doc = json.load(f)

    title = doc.get('web_metadata', {}).get('title', 'N/A')

    print(f"\n{'='*80}")
    print(f"TEST DOCUMENT")
    print(f"{'='*80}")
    print(f"Title: {title}")
    print(f"{'='*80}\n")

    enriched = enrich_document_final(
        doc, law_extractor, keyword_extractor, theme_extractor,
        profession_extractor, summary_generator, category_classifier,
        confidence_calculator, logger, save_graph=save_graph
    )

    if enriched:
        meta = enriched['semantic_metadata']
        conf = meta['confidence']

        print(f"\n{'='*80}")
        print("ENRICHMENT RESULTS - FINAL CORRECTED")
        print(f"{'='*80}\n")

        print(f"SUMMARY:")
        print(f"  {meta['sintesi']}\n")

        print(f"CATEGORY: {meta['categoria_principale']}\n")

        print(f"LAWS ({len(meta['articoli_legge'])}):")
        for law in meta['articoli_legge'][:8]:
            print(f"  • {law}")
        print()

        print(f"KEYWORDS ({len(meta['parole_chiave'])}):")
        for i, kw in enumerate(meta['parole_chiave'], 1):
            print(f"  {i}. {kw}")
        print()

        print(f"THEMES ({len(meta['temi_principali'])}):")
        for tema in meta['temi_principali']:
            print(f"  • {tema}")
        print()

        if meta.get('categorie_professionali'):
            print(f"PROFESSIONS ({len(meta['categorie_professionali'])}):")
            for prof in meta['categorie_professionali']:
                print(f"  • {prof}")
            print()

        print(f"{'='*80}")
        print("CONFIDENCE ANALYSIS")
        print(f"{'='*80}")
        print(f"Overall: {conf['overall_score']:.3f}")
        print(f"Level: {conf['confidence_level']}")
        print(f"Review: {'YES ⚠' if conf['needs_review'] else 'NO ✓'}\n")

        print("Components:")
        for component, score in conf['components'].items():
            bar = '█' * int(score * 20)
            print(f"  {component.capitalize():12s}: {bar:20s} {score:.3f}")

        if conf['review_reasons']:
            print(f"\nReview Reasons:")
            for reason in conf['review_reasons']:
                print(f"  • {reason}")

        print(f"\n{'='*80}\n")

        test_path = Config.ENRICHED_DIR / f"TEST_FINAL_{test_file.name}"
        with open(test_path, 'w', encoding='utf-8') as f:
            json.dump(enriched, f, ensure_ascii=False, indent=2)

        print(f"✓ Saved: {test_path.name}")
        print(f"✓ Log: {log_file.name}\n")

        if save_graph:
            print(f"✓ Graph saved in: {Config.GRAPH_DIR}\n")

    else:
        print("✗ ENRICHMENT FAILED\n")

def batch_process_all():

    # Versione batch con EmbeddingGemma
    print("\n" + "="*80)
    print("BATCH PROCESSING - ALL DOCUMENTS (EmbeddingGemma Edition)")
    print("="*80 + "\n")

    if not Config.setup():
        print("✗ Setup failed")
        return

    logger, log_file = setup_logging(Config.LOG_DIR)

    # LLM setup
    llm_client = None
    if Config.USE_LLM_SUMMARY:
        if install_ollama() and start_ollama() and pull_model(Config.OLLAMA_MODEL):
            llm_client = OllamaClient(model=Config.OLLAMA_MODEL)
        else:
            print("⚠ LLM setup failed, using fallback summary\n")
    else:
        print("Using structured fallback summary (no LLM)\n")

    # EMBEDDING MODEL
    print("[Setup] Initializing embedding model...")
    embedding_model = load_embedding_model(use_gemma=Config.USE_EMBEDDING_GEMMA)
    print("✓ Ready\n")

    # Initialize components
    law_extractor = LawExtractor()
    keyword_extractor = DomainAwareTFIDFExtractor(embedding_model, Config.DOMAIN_TERMS)
    theme_extractor = GenericThemeExtractor(embedding_model)
    profession_extractor = ImprovedProfessionExtractor(
        embedding_model,
        Config.KNOWN_PROFESSIONS,
        Config.PROFESSION_BLACKLIST
    )
    summary_generator = ReliableSummaryGenerator(
        llm_client,
        embedding_model,
        Config.USE_LLM_SUMMARY
    )
    category_classifier = DomainAwareCategoryClassifier(
        embedding_model,
        Config.DOCUMENT_CATEGORIES,
        Config.CATEGORY_TERMS
    )
    confidence_calculator = GlobalConfidenceCalculator()

    # Get all JSON files
    json_files = sorted([f for f in Config.JSON_DIR.glob("*.json")
                         if not f.name.startswith('vector_db')])

    print(f"Found {len(json_files)} documents\n")

    success_count = 0
    fail_count = 0
    confidence_stats = {'HIGH': 0, 'MEDIUM': 0, 'LOW': 0}

    for i, json_file in enumerate(json_files, 1):
        print(f"\n[{i}/{len(json_files)}] Processing: {json_file.name[:60]}")

        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                doc = json.load(f)

            enriched = enrich_document_final(
                doc, law_extractor, keyword_extractor, theme_extractor,
                profession_extractor, summary_generator, category_classifier,
                confidence_calculator, logger, save_graph=True
            )

            if enriched:
                output_path = Config.ENRICHED_DIR / json_file.name
                with open(output_path, 'w', encoding='utf-8') as f:
                    json.dump(enriched, f, ensure_ascii=False, indent=2)

                conf_level = enriched['semantic_metadata']['confidence']['confidence_level']
                confidence_stats[conf_level] += 1

                success_count += 1
                print(f"  ✓ Saved | Confidence: {conf_level}")
            else:
                fail_count += 1
                print(f"  ✗ Failed (Text too short or enrichment error)")

        except Exception as e:
            fail_count += 1
            print(f"  ✗ Error: {e}")
            logger.error(f"FATAL ERROR processing {json_file.name}: {e}")

    print(f"\n{'='*80}")
    print(f"BATCH COMPLETE")
    print(f"{'='*80}")
    print(f"Success: {success_count}")
    print(f"Failed: {fail_count}")
    print(f"Total: {len(json_files)}")
    print(f"\nConfidence Distribution:")
    # Prevent division by zero if all failed
    total_success = max(success_count, 1)
    print(f"  HIGH:   {confidence_stats['HIGH']} ({confidence_stats['HIGH']/total_success*100:.1f}%)")
    print(f"  MEDIUM: {confidence_stats['MEDIUM']} ({confidence_stats['MEDIUM']/total_success*100:.1f}%)")
    print(f"  LOW:    {confidence_stats['LOW']} ({confidence_stats['LOW']/total_success*100:.1f}%)")
    print(f"{'='*80}\n")

# BATCH PROCESSING - LOW CONFIDENCE FIX

def reprocess_low_confidence_documents():
    """
    Riprocessa i documenti LOW ricalcolando il confidence con la logica adattiva.
    NON modifica categoria o contenuto, solo ricalcola gli score.
    """
    print("\n" + "="*80)
    print("LOW CONFIDENCE DOCUMENTS - ADAPTIVE REPROCESSING")
    print("="*80)

    enriched_files = list(Config.ENRICHED_DIR.glob("*.json"))

    if not enriched_files:
        print("⚠ Nessun documento arricchito trovato")
        return

    print(f"\nAnalyzing {len(enriched_files)} documents...\n")

    # Inizializza calculator con la nuova logica
    confidence_calculator = GlobalConfidenceCalculator()

    stats = {'initial_low': 0, 'recomputed_high': 0, 'recomputed_medium': 0, 'still_low': 0}

    for enriched_file in enriched_files:
        with open(enriched_file, 'r', encoding='utf-8') as f:
            doc = json.load(f)

        old_conf = doc.get('semantic_metadata', {}).get('confidence', {})
        old_level = old_conf.get('confidence_level')

        if old_level == "LOW":
            stats['initial_low'] += 1

            # Estrai i componenti originali
            detailed = old_conf.get('detailed_components', {})
            kw_conf = detailed.get('keywords', {})
            law_conf = detailed.get('laws', {})
            sum_conf = detailed.get('summary', {})

            # Ricalcola con logica adattiva
            new_conf = confidence_calculator.calculate(
                kw_conf,
                law_conf,
                sum_conf
            )

            new_level = new_conf['confidence_level']

            # Statistiche
            if new_level == "HIGH":
                stats['recomputed_high'] += 1
            elif new_level == "MEDIUM":
                stats['recomputed_medium'] += 1
            else:
                stats['still_low'] += 1

            # Log cambiamento
            if new_level != old_level:
                title = doc.get('web_metadata', {}).get('title', 'N/A')[:60]
                adapted = new_conf.get('adapted_scoring', False)

                print(f"✓ {enriched_file.name}")
                print(f"  Title: {title}")
                print(f"  {old_level} ({old_conf['overall_score']:.3f}) → {new_level} ({new_conf['overall_score']:.3f})")
                if adapted:
                    print(f"  ⚙ {new_conf['adaptation_reason']}")
                print()

                # Aggiorna il documento
                doc['semantic_metadata']['confidence'] = new_conf
                doc['semantic_metadata']['reprocessed_at'] = datetime.now().isoformat()

                # Salva
                with open(enriched_file, 'w', encoding='utf-8') as f:
                    json.dump(doc, f, ensure_ascii=False, indent=2)

    # Summary finale
    print("="*80)
    print("REPROCESSING RESULTS")
    print("="*80)
    print(f"Initial LOW confidence documents: {stats['initial_low']}")
    print(f"  → Recomputed as HIGH: {stats['recomputed_high']}")
    print(f"  → Recomputed as MEDIUM: {stats['recomputed_medium']}")
    print(f"  → Still LOW: {stats['still_low']}")

    if stats['initial_low'] > 0:
        improvement = (stats['recomputed_high'] + stats['recomputed_medium']) / stats['initial_low'] * 100
        print(f"\n✓ Improvement rate: {improvement:.1f}%")
    else:
        print("\n✓ No LOW confidence documents found!")

    print("\n" + "="*80)


    # Opzioni di fix
    print("\n" + "="*80)
    print("FIX OPTIONS")
    print("="*80)
    print("1. Aggiusta automaticamente documenti LOW per assenza leggi (categoria -> 'Altro')")
    print("2. Riprocessa completamente i documenti LOW")
    print("3. Esporta lista in CSV per revisione manuale")
    print("4. Esci senza modifiche")

    choice = input("\nScelta (default 1): ").strip() or "1"

    if choice == "1":
        # Fix automatico per documenti generici
        fixed = 0
        for doc_info in low_docs:
            if doc_info['law_conf'] < 0.3:  # Principalmente problema leggi
                with open(doc_info['file'], 'r', encoding='utf-8') as f:
                    doc = json.load(f)

                # Aggiorna categoria
                old_cat = doc['semantic_metadata']['categoria_principale']
                if old_cat != "Altro":
                    doc['semantic_metadata']['categoria_principale'] = "Altro"
                    doc['semantic_metadata']['fix_applied'] = {
                        'timestamp': datetime.now().isoformat(),
                        'reason': 'LOW confidence per poche leggi - documento generico',
                        'old_category': old_cat
                    }

                    # Risalva
                    with open(doc_info['file'], 'w', encoding='utf-8') as f:
                        json.dump(doc, f, ensure_ascii=False, indent=2)

                    fixed += 1
                    print(f"✓ {doc_info['file'].name}: {old_cat} → Altro")

        print(f"\n✓ {fixed}/{stats['total']} documenti aggiustati")

    elif choice == "2":
        print("\n⚠ Per riprocessare, usa batch_process_all() su questi file specifici")
        print("   Oppure implementa una funzione dedicata")

    elif choice == "3":
        # Esporta CSV
        csv_path = Config.LOG_DIR / f"low_confidence_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        with open(csv_path, 'w', encoding='utf-8') as f:
            f.write("Filename,Title,Overall_Score,Law_Conf,Keyword_Conf,Summary_Conf,Reasons\n")
            for doc_info in low_docs:
                f.write(f'"{doc_info["file"].name}","{doc_info["title"]}",{doc_info["overall"]:.3f},{doc_info["law_conf"]:.3f},"{"| ".join(doc_info["reasons"])}"\n')

        print(f"\n✓ Lista esportata: {csv_path}")

    else:
        print("\n✓ Nessuna modifica applicata")


def reprocess_for_graphs():
    """
    Riprocessa documenti esistenti SOLO per generare i grafi mancanti.
    """
    print("\n" + "="*80)
    print("GRAPH GENERATION FOR EXISTING DOCUMENTS")
    print("="*80)

    print("\n[Setup] Initializing embedding model...")
    embedding_model = load_embedding_model(use_gemma=Config.USE_EMBEDDING_GEMMA)
    keyword_extractor = DomainAwareTFIDFExtractor(embedding_model, Config.DOMAIN_TERMS)
    print("✓ Ready\n")

    enriched_files = list(Config.ENRICHED_DIR.glob("*.json"))

    if not enriched_files:
        print("⚠ Nessun documento arricchito trovato")
        return

    print(f"Found {len(enriched_files)} enriched documents\n")

    generated = 0
    errors = 0

    for i, enriched_file in enumerate(enriched_files, 1):
        try:
            with open(enriched_file, 'r', encoding='utf-8') as f:
                doc = json.load(f)

            doc_title = doc.get('web_metadata', {}).get('title', 'N/A')[:50]
            full_text = extract_full_document_text(doc)
            print("FULLTEXT LEN =", len(full_text) if full_text else 0)

            print(f"[{i}/{len(enriched_files)}] {doc_title}...")

            # Genera grafo
            safe_title = re.sub(r'[^\w\-_]', '_', doc_title)
            graph_path = Config.GRAPH_DIR / f"EmbedRank_{safe_title}.png"

            keywords, kw_metadata, G = keyword_extractor.extract_keywords_with_confidence(
                full_text, top_n=8, save_graph=True,
                graph_path=graph_path, doc_title=doc_title
            )

            if graph_path.exists():
                print(f"  ✓ Graph saved: {graph_path.name}\n")
                generated += 1
            else:
                print(f"  ⚠ Graph not saved (possible empty graph)\n")

        except Exception as e:
            print(f"  ✗ Error: {e}\n")
            errors += 1

    print("="*80)
    print(f"✓ Completed: {generated} graphs generated, {errors} errors")
    print(f"✓ Graphs saved in: {Config.GRAPH_DIR}")

# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    print("\n" + "="*80)
    print("INAIL - FINAL CORRECTED ENRICHMENT SYSTEM (EmbeddingGemma)")
    print("="*80)

    print("\nSelect mode:")
    print("  [1] Quick test (single document)")
    print("  [2] Batch process all")
    print("  [3] Generate graphs only")
    print("  [4] Reprocess LOW confidence (adaptive scoring)")  # ← MODIFICATO

    mode = input("\nMode (default 1): ").strip() or "1"

    if mode == "2":
        batch_process_all()
    elif mode == "3":
        reprocess_for_graphs()
    elif mode == "4":
        reprocess_low_confidence_documents()  # ← MODIFICATO
    else:
        quick_test()

# ENTRY POINT

if __name__ == "__main__":
    print("\n" + "="*80)
    print("INAIL - FINAL CORRECTED ENRICHMENT SYSTEM (EmbeddingGemma)")
    print("="*80)

    mode = input("Mode? [1] Quick test  [2] Batch all (default 1): ").strip()

    if mode == "2":
        batch_process_all()
    else:
        quick_test()

MY_TOKEN = os.environ.get("HUGGINGFACE_TOKEN", "")

"""
COLAB DEBUG EXTRACTOR - Da aggiungere al notebook esistente
Estrae info di debug per running examples della tesi
"""

import json
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from pathlib import Path

# Helper per convertire numpy types in Python types
def convert_numpy_types(obj):
    """Converte ricorsivamente numpy types in Python standard types"""
    if isinstance(obj, np.integer):
        return int(obj)
    elif isinstance(obj, np.floating):
        return float(obj)
    elif isinstance(obj, np.ndarray):
        return obj.tolist()
    elif isinstance(obj, dict):
        return {key: convert_numpy_types(value) for key, value in obj.items()}
    elif isinstance(obj, list):
        return [convert_numpy_types(item) for item in obj]
    else:
        return obj

# ============================================================================
# TEST 1: THEMES - Clustering Debug
# ============================================================================

class ThemeExtractorDebug(GenericThemeExtractor):
    """Versione con debug output per themes"""

    def extract_themes_debug(self, keywords: List[str], laws: List[str],
                            document_text: str) -> Tuple[List[str], Dict]:
        """Versione con trace completo del clustering"""

        debug_info = {}

        if len(keywords) < 3:
            themes = [kw.capitalize() for kw in keywords[:3]]
            if laws:
                themes.append("Normativa")

            debug_info = {
                'n_keywords': len(keywords),
                'clustering_applied': False,
                'reason': 'Too few keywords (<3)',
                'themes': themes
            }
            return themes, debug_info

        # Embeddings
        embeddings = self.embedding_model.encode(keywords)
        n_clusters = min(4, max(2, len(keywords) // 3))

        debug_info['n_keywords'] = len(keywords)
        debug_info['k_clusters'] = n_clusters
        debug_info['keywords'] = keywords

        # Clustering
        try:
            from sklearn.cluster import AgglomerativeClustering
            clustering = AgglomerativeClustering(
                n_clusters=n_clusters,
                metric='cosine',
                linkage='average'
            )
            labels = clustering.fit_predict(embeddings)

            debug_info['clustering_applied'] = True
            debug_info['labels'] = [int(x) for x in labels]  # Convert numpy int64 to Python int

        except:
            debug_info['clustering_applied'] = False
            debug_info['error'] = 'Clustering failed'
            return [kw.capitalize() for kw in keywords[:4]], debug_info

        # Cluster assignment
        from collections import defaultdict
        clusters = defaultdict(list)
        for i, label in enumerate(labels):
            clusters[label].append(keywords[i])

        debug_info['clusters'] = {f"C{k}": v for k, v in clusters.items()}

        # Theme generation
        themes = []
        cluster_details = []

        for cluster_id, cluster_kw in clusters.items():
            cluster_info = {'cluster_id': cluster_id, 'keywords': cluster_kw}

            if len(cluster_kw) == 1:
                theme = cluster_kw[0].capitalize()
                cluster_info['strategy'] = 'single'
                cluster_info['theme'] = theme

            elif len(cluster_kw) == 2:
                theme = f"{cluster_kw[0].capitalize()} e {cluster_kw[1]}"
                cluster_info['strategy'] = 'pair'
                cluster_info['theme'] = theme

            else:
                # Centroid strategy
                cluster_embs = self.embedding_model.encode(cluster_kw)
                centroid = np.mean(cluster_embs, axis=0)

                distances = [
                    (kw, float(cosine_similarity([emb], [centroid])[0][0]))
                    for kw, emb in zip(cluster_kw, cluster_embs)
                ]
                distances.sort(key=lambda x: x[1], reverse=True)

                top2 = distances[:2]
                theme = f"{top2[0][0].capitalize()} e {top2[1][0]}"

                cluster_info['strategy'] = 'centroid'
                cluster_info['distances'] = {kw: round(score, 3) for kw, score in distances}
                cluster_info['top2'] = [top2[0][0], top2[1][0]]
                cluster_info['theme'] = theme

            themes.append(theme)
            cluster_details.append(cluster_info)

        debug_info['cluster_details'] = cluster_details

        # Add normativa if needed
        if laws and len(laws) >= 2:
            if not any("normativ" in t.lower() for t in themes):
                themes.append("Normativa")
                debug_info['normativa_added'] = True

        debug_info['final_themes'] = themes[:4]

        return themes[:4], debug_info


# ============================================================================
# TEST 2: CATEGORY - Scoring Debug
# ============================================================================

class CategoryClassifierDebug(DomainAwareCategoryClassifier):
    """Versione con debug output per category classification"""

    def classify_debug(self, keywords: List[str], themes: List[str],
                      laws: List[str]) -> Tuple[str, Dict]:
        """Versione con trace completo dello scoring"""

        debug_info = {
            'input': {
                'keywords': keywords,
                'themes': themes,
                'laws': laws
            }
        }

        all_text = ' '.join(keywords + themes).lower()

        # LIVELLO 1: Domain term scoring
        domain_scores = {}
        domain_details = {}

        for category, terms in self.category_terms.items():
            matches = sum(1 for term in terms if term in all_text)
            score = matches / max(len(terms), 1)
            domain_scores[category] = score
            domain_details[category] = {
                'score': round(score, 3),
                'matches': matches,
                'total_terms': len(terms),
                'matched_terms': [term for term in terms if term in all_text]
            }

        # Generic overlap for categories without specific terms
        for category in self.valid_categories:
            if category not in domain_scores:
                cat_words = set(category.lower().split())
                text_words = set(all_text.split())
                overlap = len(cat_words & text_words)
                score = overlap / max(len(cat_words), 1)
                domain_scores[category] = score
                domain_details[category] = {
                    'score': round(score, 3),
                    'strategy': 'generic_overlap',
                    'overlap': overlap
                }

        debug_info['domain_scoring'] = domain_details

        # Penalize "Normativa"
        if "Normativa e adempimenti" in domain_scores:
            specific_categories = [cat for cat in domain_scores.keys()
                                  if cat != "Normativa e adempimenti"]
            max_specific_score = max([domain_scores[cat] for cat in specific_categories], default=0)

            if max_specific_score > 0.15:
                original_score = domain_scores["Normativa e adempimenti"]
                domain_scores["Normativa e adempimenti"] *= 0.3
                debug_info['normativa_penalty'] = {
                    'applied': True,
                    'original_score': round(original_score, 3),
                    'penalized_score': round(domain_scores["Normativa e adempimenti"], 3),
                    'reason': f'max_specific_score={max_specific_score:.3f} > 0.15'
                }

        # Top 5 candidates
        top_candidates = sorted(domain_scores.items(), key=lambda x: x[1], reverse=True)[:5]
        debug_info['top5_candidates'] = [
            {'category': cat, 'domain_score': round(score, 3)}
            for cat, score in top_candidates
        ]

        # LIVELLO 2: Semantic similarity
        description = f"""Keywords: {', '.join(keywords[:10])}.
Temi: {', '.join(themes[:3])}.
Leggi: {', '.join(laws[:3]) if laws else 'Generiche'}."""

        desc_emb = self.embedding_model.encode([description])

        semantic_scores = []
        best_category = None
        best_score = 0

        for category, domain_score in top_candidates:
            cat_idx = self.valid_categories.index(category)
            sem_score = float(cosine_similarity(desc_emb, [self.category_embeddings[cat_idx]])[0][0])

            # Blending: 70% domain + 30% semantic
            combined_score = 0.7 * domain_score + 0.3 * sem_score

            semantic_scores.append({
                'category': category,
                'domain_score': round(domain_score, 3),
                'semantic_score': round(sem_score, 3),
                'combined_score': round(combined_score, 3),
                'blending': '0.7*domain + 0.3*semantic'
            })

            if combined_score > best_score:
                best_score = combined_score
                best_category = category

        debug_info['semantic_scoring'] = semantic_scores
        debug_info['best_match'] = {
            'category': best_category,
            'final_score': round(best_score, 3),
            'threshold': Config.CATEGORY_THRESHOLD
        }

        # Fallback check
        if best_score < Config.CATEGORY_THRESHOLD:
            debug_info['fallback'] = {
                'applied': True,
                'reason': f'best_score ({best_score:.3f}) < threshold ({Config.CATEGORY_THRESHOLD})',
                'final_category': 'Altro'
            }
            return "Altro", debug_info

        debug_info['final_category'] = best_category
        return best_category, debug_info


# ============================================================================
# TEST 3: PROFESSIONS - Threshold + Blacklist Debug
# ============================================================================

class ProfessionExtractorDebug(ImprovedProfessionExtractor):
    """Versione con debug output per profession extraction"""

    def extract_professions_debug(self, document_text: str, keywords: List[str],
                                  themes: List[str], category: str,
                                  top_k: int = 3, threshold: float = 0.55
                                 ) -> Tuple[List[str], Dict]:
        """Versione con trace completo della selezione"""

        debug_info = {
            'input': {
                'category': category,
                'top_keywords': keywords[:8],
                'themes': themes[:3]
            },
            'config': {
                'top_k': top_k,
                'threshold': threshold,
                'blacklist': list(self.blacklist)
            }
        }

        # CHECK: documenti normativi/informativi generici
        if category in ["Normativa e adempimenti", "Altro"]:
            debug_info['skip_reason'] = f'Categoria "{category}" indica documento generico/normativo'
            debug_info['final_professions'] = ['Nessuna (documento generico)']
            return [], debug_info

        doc_desc = f"""Settore: {category}.
Parole chiave: {', '.join(keywords[:8])}.
Temi: {', '.join(themes[:3])}.
Contenuto: {document_text[:1500]}"""

        # Compute similarities
        doc_emb = self.embedding_model.encode([doc_desc])
        similarities = cosine_similarity(doc_emb, self.profession_embeddings)[0]

        ranked = sorted(
            zip(self.known_professions, similarities),
            key=lambda x: x[1],
            reverse=True
        )

        # Top 10 for analysis
        debug_info['top10_raw'] = [
            {'profession': prof, 'similarity': round(float(score), 3)}
            for prof, score in ranked[:10]
        ]

        # Filter process
        selected = []
        blacklisted = []
        below_threshold = []

        for prof, score in ranked:
            if prof in self.blacklist:
                blacklisted.append({
                    'profession': prof,
                    'similarity': round(float(score), 3),
                    'reason': 'in blacklist'
                })
                continue

            if score >= threshold:
                selected.append(prof)
                if len(selected) >= top_k:
                    break
            else:
                below_threshold.append({
                    'profession': prof,
                    'similarity': round(float(score), 3),
                    'reason': f'below threshold ({threshold})'
                })

        debug_info['filtering'] = {
            'blacklisted': blacklisted[:5],  # Top 5 blacklisted
            'below_threshold': below_threshold[:5],  # Top 5 below threshold
            'selected': [
                {'profession': prof, 'rank': i+1}
                for i, prof in enumerate(selected)
            ]
        }

        # FALLBACK MIGLIORATO: check se best score è troppo basso
        if not selected:
            best_non_blacklisted = None
            best_score = 0

            for prof, score in ranked:
                if prof not in self.blacklist:
                    best_non_blacklisted = prof
                    best_score = score
                    break

            # Se il migliore è sotto 0.45, è un documento generico
            if best_score < 0.45:
                debug_info['fallback'] = {
                    'applied': True,
                    'reason': f'best_score ({best_score:.3f}) < 0.45 - documento generico',
                    'decision': 'Nessuna professione specifica (documento informativo/normativo)',
                    'best_candidate': best_non_blacklisted,
                    'best_score': round(float(best_score), 3)
                }
                selected = []  # Lista vuota per documenti generici
            else:
                # Fallback normale (0.40 < score < 0.55)
                selected = [best_non_blacklisted]
                debug_info['fallback'] = {
                    'applied': True,
                    'profession': best_non_blacklisted,
                    'similarity': round(float(best_score), 3),
                    'reason': 'no profession above threshold, using best non-blacklisted (weak match)'
                }

        debug_info['final_professions'] = selected if selected else ['Nessuna (documento generico)']

        return selected, debug_info


# ============================================================================
# RUNNER PRINCIPALE
# ============================================================================

def extract_debug_info_for_thesis():
    """
    Esegue l'enrichment su 1 documento con output di debug
    per i 3 running examples della tesi
    """

    print("\n" + "="*80)
    print("DEBUG EXTRACTOR - Running Examples per Tesi")
    print("="*80 + "\n")

    # Setup paths
    json_dir = Path('/content/drive/MyDrive/INAIL_Thesis_Data/json')

    if not json_dir.exists():
        print("✗ Cartella JSON non trovata")
        return

    json_files = [f for f in json_dir.glob("*.json")
                  if not f.name.startswith('vector_db')]

    if not json_files:
        print("✗ Nessun JSON trovato")
        return

    print(f"Trovati {len(json_files)} documenti\n")

    # Select document
    test_file = json_files[0]
    print(f"📄 Documento: {test_file.name}\n")

    # Load document
    with open(test_file, 'r', encoding='utf-8') as f:
        doc = json.load(f)

    title = doc.get('web_metadata', {}).get('title', 'N/A')
    full_text = extract_full_document_text(doc)

    print(f"Titolo: {title[:70]}")
    print(f"Testo: {len(full_text)} caratteri\n")

    # Setup models (usa quelli già caricati nel notebook)
    print("⏳ Caricamento modelli...")
    embedding_model = load_embedding_model(use_gemma=True)

    # Extract components
    law_extractor = LawExtractor()
    laws, _ = law_extractor.extract_with_confidence(full_text)

    keyword_extractor = DomainAwareTFIDFExtractor(embedding_model, Config.DOMAIN_TERMS)
    keywords, _, _ = keyword_extractor.extract_keywords_with_confidence(
        full_text, top_n=8, save_graph=False
    )

    print("\n" + "="*80)
    print("TEST 1: THEMES CLUSTERING")
    print("="*80 + "\n")

    theme_extractor_debug = ThemeExtractorDebug(embedding_model)
    themes, theme_debug = theme_extractor_debug.extract_themes_debug(
        keywords, laws, full_text
    )

    # Convert numpy types before printing
    theme_debug = convert_numpy_types(theme_debug)
    print(json.dumps(theme_debug, indent=2, ensure_ascii=False))

    print("\n" + "="*80)
    print("TEST 2: CATEGORY CLASSIFICATION")
    print("="*80 + "\n")

    category_classifier_debug = CategoryClassifierDebug(
        embedding_model,
        Config.DOCUMENT_CATEGORIES,
        Config.CATEGORY_TERMS
    )
    category, category_debug = category_classifier_debug.classify_debug(
        keywords, themes, laws
    )

    # Convert numpy types before printing
    category_debug = convert_numpy_types(category_debug)
    print(json.dumps(category_debug, indent=2, ensure_ascii=False))

    print("\n" + "="*80)
    print("TEST 3: PROFESSION EXTRACTION")
    print("="*80 + "\n")

    profession_extractor_debug = ProfessionExtractorDebug(
        embedding_model,
        Config.KNOWN_PROFESSIONS,
        Config.PROFESSION_BLACKLIST
    )
    professions, profession_debug = profession_extractor_debug.extract_professions_debug(
        full_text, keywords, themes, category,
        top_k=3, threshold=Config.PROFESSION_THRESHOLD
    )

    # Convert numpy types before printing
    profession_debug = convert_numpy_types(profession_debug)
    print(json.dumps(profession_debug, indent=2, ensure_ascii=False))

    # Save to file
    output_path = Path('/content/drive/MyDrive/INAIL_Thesis_Data/logs/thesis_debug_output.json')

    all_debug = {
        'document': {
            'title': title,
            'file': test_file.name
        },
        'test1_themes': theme_debug,
        'test2_category': category_debug,
        'test3_professions': profession_debug
    }

    # Convert all numpy types before saving
    all_debug = convert_numpy_types(all_debug)

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(all_debug, f, indent=2, ensure_ascii=False)

    print("\n" + "="*80)
    print(f"✓ Debug output salvato: {output_path}")
    print("="*80 + "\n")


# ============================================================================
# DA ESEGUIRE NEL NOTEBOOK
# ============================================================================

# Aggiungi questa cella alla fine del tuo notebook Colab:
extract_debug_info_for_thesis()