# -*- coding: utf-8 -*-
"""Osha_Docling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZMueJJieVvL8q4lsQo0FOoAwU5Iho9r

# **OSHA Publications Scraper con Docling + VLM Integration**
"""

import re
import requests
from bs4 import BeautifulSoup
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional, Any, List
import tempfile
import os
import base64
from io import BytesIO

# Installazione dipendenze
!pip install docling pymupdf pillow -q

from docling.document_converter import DocumentConverter, PdfFormatOption
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions, PictureDescriptionVlmOptions
from docling_core.types.doc import ImageRefMode

# Per visualizzazione in Colab
from IPython.display import display, HTML, Image as IPImage
import pandas as pd

# INSTALLAZIONE VERBOSE (mostra tutto)
!pip install docling "docling[vlm]" transformers torch pillow accelerate requests beautifulsoup4 lxml

# OSHA Publications Scraper con Docling + VLM + ENHANCED TABLE EXTRACTION

import re
from typing import Dict, List, Any
from pathlib import Path

import re
import requests
from bs4 import BeautifulSoup
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional, Any, List
from urllib.parse import quote_plus
import unicodedata
import time
import random
import re
from typing import Dict, List, Any

# ENHANCED TABLE PARSER

def extract_table_metadata_enhanced(table_lines: List[str], context_lines: List[str]) -> Dict[str, Any]:

    # Estrae metadati avanzati da tabelle Markdown con context awareness

    metadata = {
        'caption': 'N/A',
        'title': 'N/A',
        'headers': [],
        'rows': [],
        'num_rows': 0,
        'num_columns': 0,
        'content_type': 'unknown'
    }

    # 1) CERCA CAPTION/TITOLO nelle linee precedenti
    descriptive_line = None  # FIX: Inizializza per evitare UnboundLocalError
    for line in reversed(context_lines[-10:]):
        clean = line.strip()
        if not clean or clean.startswith('#'):
            continue

        # Pattern per caption
        caption_patterns = [
            r'(?i)^(?:table|tabella|tab\.|tbl\.?)\s*\d*[\.:]\s*(.+)',
            r'(?i)^(?:table|tabella)\s+\d+[\s\-–—]+(.+)',
            r'(?i)^caption[\s:]+(.+)'
        ]

        for pattern in caption_patterns:
            match = re.search(pattern, clean)
            if match:
                metadata['caption'] = match.group(1).strip()
                metadata['title'] = clean
                break

        if metadata['caption'] != 'N/A':
            break

        # FIX: Check descrittivo DENTRO loop (usa ultima line valida)
        if len(clean) > 20 and not re.match(r'^[\|\-\s]+$', clean):
            descriptive_line = clean

    # Fallback caption da descriptive_line
    if metadata['caption'] == 'N/A' and descriptive_line:
        metadata['caption'] = descriptive_line[:150]

    # 2) ESTRAI HEADERS
    header_row = None
    separator_idx = -1

    for idx, line in enumerate(table_lines):
        if re.match(r'^\s*\|[\s\-\|:]+\|\s*$', line):
            separator_idx = idx
            if idx > 0:
                header_row = table_lines[idx - 1]
            break

    if header_row:
        headers_raw = [cell.strip() for cell in header_row.split('|') if cell.strip()]
        # FIX: Skip se è solo trattini (es. "|----|")
        metadata['headers'] = [h for h in headers_raw if h and not re.match(r'^[\-\s\|]+$', h)]
        metadata['num_columns'] = len(metadata['headers'])
    else:
        # Fallback senza separatore
        if len(table_lines) >= 2:
            first_row = table_lines[0]
            headers_raw = [cell.strip() for cell in first_row.split('|') if cell.strip() and len(cell.strip()) > 0 and not re.match(r'^[\-\s\|]+$', cell.strip())]
            if len(headers_raw) >= 2:
                metadata['headers'] = headers_raw[:2]
                metadata['num_columns'] = len(metadata['headers'])

    # 3) ESTRAI ROWS (skip celle vuote consecutive)
    if separator_idx >= 0:
        data_rows = table_lines[separator_idx + 1:]
    else:
        data_rows = table_lines[1:] if len(table_lines) > 1 and metadata['headers'] else table_lines

    for line in data_rows:
        if not line.strip() or re.match(r'^\s*[\|\-\s]+$', line):
            continue
        cells_raw = line.split('|')
        cells = [cell.strip() for cell in cells_raw if cell.strip()]  # Skip vuote
        if len(cells) >= 1:  # Almeno una cella non vuota
            # Pad con '' se < num_columns
            while len(cells) < metadata['num_columns']:
                cells.append('')
            metadata['rows'].append(cells[:metadata['num_columns']])  # Taglia extra

    metadata['num_rows'] = len(metadata['rows'])

    # 4) CONTENT TYPE (migliorato)
    if metadata['headers']:
        headers_text = ' '.join(metadata['headers']).lower()
        if any(kw in headers_text for kw in ['risk', 'hazard', 'danger', 'injury']):
            metadata['content_type'] = 'risk_assessment'
        elif any(kw in headers_text for kw in ['statistic', 'number', 'percentage', '%', 'rate']):
            metadata['content_type'] = 'statistical_data'
        elif any(kw in headers_text for kw in ['checklist', 'requirement', 'compliance']):
            metadata['content_type'] = 'compliance_checklist'
        elif any(kw in headers_text for kw in ['dx', 'a1', 'a2', 'read out', 'multiple answers']):
            metadata['content_type'] = 'survey_questionnaire'  # NUOVO per table_41

    if metadata['content_type'] == 'unknown' and metadata['rows']:
        rows_text = ' '.join(' '.join(row).lower() for row in metadata['rows'])
        if any(kw in rows_text for kw in ['website', 'period', 'data source', 'years', 'covered by']):
            metadata['content_type'] = 'data_source_metadata'
        elif any(kw in rows_text for kw in ['workload', 'harassment', 'bullying', 'digital technologies', 'automation', 'emotional burden']):
            metadata['content_type'] = 'psychosocial_risks'  # NUOVO per table_1
        else:
            metadata['content_type'] = 'general_data'

    return metadata

def format_table_content_readable(metadata: Dict[str, Any]) -> str:

    # Formatta contenuto tabella in modo leggibile
    lines = []

    if metadata['headers']:
        header_line = ' | '.join([h if h else '' for h in metadata['headers']])  # Gestisci empty
        lines.append(header_line)
        lines.append('-' * len(header_line))

    for row in metadata['rows']:
        if metadata['headers']:
            padded_cells = []
            for i, cell in enumerate(row):
                cell_str = str(cell)
                if re.match(r'^https?://', cell_str):
                    max_len = 1000
                else:
                    max_len = 500
                cell_str = cell_str[:max_len]
                header_len = len(metadata['headers'][i]) if i < len(metadata['headers']) and metadata['headers'][i] else len(cell_str)
                padded_cells.append(cell_str.ljust(header_len))
            lines.append(' | '.join(padded_cells))
        else:
            lines.append(' • ' + ' | '.join(str(c)[:500] for c in row))

    return '\n'.join(lines)

# DOCUMENT STRUCTURE ANALYSIS

def analyze_document_structure_enhanced(doc) -> Dict[str, Any]:

    # Analizza struttura documento con ENHANCED TABLE PARSING
    structure = {
        'num_tables': 0,
        'num_figures': 0,
        'num_headings': 0,
        'headings': [],
        'tables': [],
        'figures': []
    }

    try:
        markdown = doc.export_to_markdown()
        lines = markdown.split('\n')

        # 1) HEADINGS (invariato)
        for i, line in enumerate(lines):
            if line.strip().startswith('#'):
                level = len(line) - len(line.lstrip('#'))
                text = line.lstrip('#').strip()
                structure['num_headings'] += 1
                structure['headings'].append({
                    'type': f'heading_level_{level}',
                    'text': text[:200],
                    'position': i,
                    'level': level
                })

        # 2) TABLES - ENHANCED PARSING
        in_table = False
        current_table_lines = []
        table_start_idx = -1

        for i, line in enumerate(lines):
            # Identifica inizio tabella
            if '|' in line and ('-' in line or '─' in line or ':' in line):
                if not in_table:
                    in_table = True
                    table_start_idx = i
                    current_table_lines = []

            if in_table:
                if '|' in line:
                    current_table_lines.append(line)
                else:
                    # Fine tabella
                    if current_table_lines and len(current_table_lines) >= 2:
                        # Estrai context (linee prima della tabella)
                        context_start = max(0, table_start_idx - 15)
                        context_lines = lines[context_start:table_start_idx]

                        # ENHANCED PARSING
                        metadata = extract_table_metadata_enhanced(
                            current_table_lines,
                            context_lines
                        )

                        # Formatta contenuto
                        readable_content = format_table_content_readable(metadata)

                        structure['num_tables'] += 1
                        structure['tables'].append({
                            'table_id': f'table_{structure["num_tables"]}',
                            'caption': metadata['caption'],
                            'title': metadata['title'],
                            'text_content': readable_content,
                            'raw_markdown': '\n'.join(current_table_lines),
                            'num_rows': metadata['num_rows'],
                            'num_columns': metadata['num_columns'],
                            'potential_columns': metadata['headers'],
                            'content_type': metadata['content_type'],
                            'position': table_start_idx,
                            'enhanced_parsing': True
                        })

                    in_table = False
                    current_table_lines = []

        # Gestisci tabella che termina a fine documento
        if in_table and current_table_lines and len(current_table_lines) >= 2:
            context_start = max(0, table_start_idx - 15)
            context_lines = lines[context_start:table_start_idx]

            metadata = extract_table_metadata_enhanced(current_table_lines, context_lines)
            readable_content = format_table_content_readable(metadata)

            structure['num_tables'] += 1
            structure['tables'].append({
                'table_id': f'table_{structure["num_tables"]}',
                'caption': metadata['caption'],
                'title': metadata['title'],
                'text_content': readable_content,
                'raw_markdown': '\n'.join(current_table_lines),
                'num_rows': metadata['num_rows'],
                'num_columns': metadata['num_columns'],
                'potential_columns': metadata['headers'],
                'content_type': metadata['content_type'],
                'position': table_start_idx,
                'enhanced_parsing': True
            })

        # 3) FIGURES
        for i, line in enumerate(lines):
            if '<!-- image -->' in line.lower() or (line.strip().startswith('![') and '](' in line):
                structure['num_figures'] += 1
                caption = 'N/A'
                for j in range(i+1, min(len(lines), i+5)):
                    candidate = lines[j].strip()
                    if candidate and not candidate.startswith('#'):
                        caption = candidate
                        break

                structure['figures'].append({
                    'figure_id': f'figure_{structure["num_figures"]}',
                    'caption': caption,
                    'position': i,
                    'vlm_description': None
                })

    except Exception as e:
        print(f"[!] Errore analisi: {e}")

    return structure

# EXPORT TABLES

def export_tables_to_files_enhanced(tables: List[Dict], doc_id: str, tables_dir: Path) -> List[str]:

    # Esporta tabelle con METADATI ARRICCHITI
    if not tables:
        return []

    doc_tables_dir = tables_dir / doc_id
    doc_tables_dir.mkdir(parents=True, exist_ok=True)
    exported_tables = []

    for table in tables:
        table_id = table['table_id']
        txt_path = doc_tables_dir / f"{table_id}.txt"

        try:
            with open(txt_path, 'w', encoding='utf-8') as f:
                f.write("="*80 + "\n")
                f.write(f"TABELLA: {table_id}")
                if table.get('enhanced_parsing'):
                    f.write(" (Enhanced Parsing)")
                f.write("\n" + "="*80 + "\n\n")

                # METADATI ARRICCHITI
                f.write(" METADATI TABELLA\n")
                f.write("-"*80 + "\n")
                f.write(f"Titolo/Caption: {table.get('title', 'N/A')}\n")
                f.write(f"Caption estratta: {table.get('caption', 'N/A')}\n")
                f.write(f"Tipo contenuto: {table.get('content_type', 'N/A')}\n")
                f.write(f"Righe dati: {table.get('num_rows', 'N/A')}\n")
                f.write(f"Colonne: {table.get('num_columns', len(table.get('potential_columns', [])))}\n")
                f.write(f"Posizione nel documento: {table.get('position', 'N/A')}\n")
                f.write("\n")

                # HEADERS/COLONNE
                if table.get('potential_columns'):
                    f.write(" COLONNE IDENTIFICATE:\n")
                    for idx, col in enumerate(table['potential_columns'], 1):
                        f.write(f" {idx}. {col}\n")
                    f.write("\n")

                # CONTENUTO PULITO
                f.write(" CONTENUTO (formattato):\n")
                f.write("-"*80 + "\n")
                f.write(table['text_content'])
                f.write("\n" + "-"*80 + "\n\n")

                # RAW MARKDOWN (per debug)
                if table.get('raw_markdown'):
                    f.write(" MARKDOWN ORIGINALE (debug):\n")
                    f.write("-"*80 + "\n")
                    f.write(table['raw_markdown'])
                    f.write("\n" + "-"*80 + "\n")

            exported_tables.append(str(txt_path))
            print(f" [+] {txt_path.name} ({' enhanced' if table.get('enhanced_parsing') else 'standard'})")
        except Exception as e:
            print(f" [!] Errore export tabella {table_id}: {e}")

    return exported_tables

# CONFIGURAZIONE

class OSHAConfig:

    # Path su Drive
    OUTPUT_DIR = Path('/content/drive/MyDrive/OSHA_Thesis_Data')
    PDF_DIR = OUTPUT_DIR / 'pdfs'
    JSON_DIR = OUTPUT_DIR / 'json'
    IMAGES_DIR = OUTPUT_DIR / 'images'
    TABLES_DIR = OUTPUT_DIR / 'tables'
    KEYWORDS_DIR = OUTPUT_DIR / 'keywords'  # Directory separata per keywords

    # VLM Configuration
    VLM_ENABLED = True
    VLM_MODEL = "HuggingFaceTB/SmolVLM-256M-Instruct"
    VLM_PROMPT = """Describe this technical document image in detail for academic research. Focus on:
- Main content type (diagram, chart, photo, schematic)
- Key visual elements and their relationships
- Any visible text, labels, or numerical data
- Technical details relevant to workplace safety or industrial processes
Be precise and comprehensive."""

    USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    TIMEOUT = 30

    @classmethod
    def setup_directories(cls):
        # Crea tutte le directory necessarie
        for dir_path in [cls.OUTPUT_DIR, cls.PDF_DIR, cls.JSON_DIR,
                        cls.IMAGES_DIR, cls.TABLES_DIR, cls.KEYWORDS_DIR]:
            dir_path.mkdir(exist_ok=True, parents=True)
        print(f"[INFO] Directory configurate: {cls.OUTPUT_DIR}")

    @classmethod
    def verify_directories(cls):
        # Verifica che tutte le directory esistano
        all_exist = True
        for name, path in [
            ('OUTPUT', cls.OUTPUT_DIR),
            ('PDFs', cls.PDF_DIR),
            ('JSON', cls.JSON_DIR),
            ('Images', cls.IMAGES_DIR),
            ('Tables', cls.TABLES_DIR),
            ('Keywords', cls.KEYWORDS_DIR)
        ]:
            exists = path.exists()
            status = "✅" if exists else "❌"
            print(f"  {status} {name}: {path}")
            all_exist = all_exist and exists
        return all_exist

# GOOGLE DRIVE MOUNTING

def mount_google_drive():
    """Monta Google Drive"""
    try:
        from google.colab import drive
        drive.mount('/content/drive', force_remount=False)
        print("[SUCCESS] Drive montato\n")
        return True
    except Exception as e:
        print(f"[ERROR] Drive non disponibile: {e}\n")
        return False

# DOCLING INITIALIZATION - IDENTICA A INAIL

def initialize_docling_converter():

    # Inizializza Docling per parsing PDF
    from docling.datamodel.pipeline_options import PdfPipelineOptions
    from docling.datamodel.base_models import InputFormat
    from docling.document_converter import DocumentConverter, PdfFormatOption

    pipeline_options = PdfPipelineOptions()
    pipeline_options.generate_picture_images = True
    pipeline_options.images_scale = 2.0
    pipeline_options.do_ocr = True
    pipeline_options.do_picture_description = False

    converter = DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
        }
    )

    print(f"[INFO] Docling OK | VLM: {'ON' if OSHAConfig.VLM_ENABLED else 'OFF'} | Enhanced Tables: ON\n")
    return converter

# URL UTILITIES

def normalize_query(q: str) -> str:

    # Normalizza query di ricerca
    q = unicodedata.normalize("NFKC", q).strip().lower()
    return " ".join(q.split()).replace("'", "'")


def build_osha_search_url(query: str = "", lang: str = "en", page: int = 0,
                          sort: str = "field_publication_date") -> str:

    # Costruisce URL di ricerca OSHA - MODIFICATO per query vuota (lista generale)
    if lang not in {"it", "en"}:
        raise ValueError("Il parametro 'lang' deve essere 'it' oppure 'en'.")
    if page < 0:
        raise ValueError("Pagina >= 0")

    base_url = f"https://osha.europa.eu/{lang}/publications"

    if query.strip():
        q = normalize_query(query)
        encoded_query = quote_plus(q)
        url = f"{base_url}?search_api_fulltext={encoded_query}&sort_by={sort}"
    else:
        # Senza query: lista generale delle pubblicazioni, ordinata per data DESC
        url = f"{base_url}?sort_bef_combine=field_publication_date DESC"

    if page > 0:
        separator = '&' if '?' in url else '?'
        url += f"{separator}page={page}"

    return url

# ESTRAZIONE LINK

def get_osha_publication_links_with_range(
    search_url: str,
    start_page: int = 0,
    end_page: int = 4,
    max_pages: Optional[int] = None
) -> List[Dict[str, str]]:

    # Estrae link pubblicazioni OSHA con range di pagine - FIX: No break <5, continua fino end_page

    publications = []
    seen_urls = set()

    print(f"\n{'='*80}")
    print(f"ESTRAZIONE LINK OSHA (LISTA PRINCIPALE, ORDINATA PER DATA)")
    print(f"{'='*80}")
    print(f"URL base: {search_url}")
    print(f"Range: pagina {start_page} → {end_page}")
    print(f"{'='*80}\n")

    session = requests.Session()
    headers = {'User-Agent': OSHAConfig.USER_AGENT}
    session.headers.update(headers)

    actual_end = min(end_page, start_page + max_pages - 1) if max_pages else end_page

    for page_num in range(start_page, actual_end + 1):
        # URL con paginazione
        if page_num == 0:
            url = search_url
        else:
            separator = '&' if '?' in search_url else '?'
            url = f"{search_url}{separator}page={page_num}"

        print(f"[Pagina {page_num + 1}] Fetching: {url}")

        # Delay progressivo
        if page_num > start_page:
            delay = 5 + (page_num - start_page) * 2
            print(f"  [~] Attesa {delay} secondi...")
            time.sleep(delay)

        try:
            response = session.get(url, timeout=30)

            if response.status_code == 403:
                print(f"  [!] 403 Forbidden - aumenta delay")
                print(f"  [INFO] Pubblicazioni raccolte: {len(publications)}")
                break

            response.raise_for_status()
            soup = BeautifulSoup(response.content, 'lxml')

            results_found = False
            page_pubs = []

            # TROVA IL CONTAINER DELLA LISTA PRINCIPALE
            view_content = soup.find('div', class_='view-content')  # Drupal views
            if not view_content:
                # Fallback: cerca sezione con "Publications available"
                pub_text = soup.find(string=re.compile(r'Publications available \(\d+\)'))
                if pub_text:
                    view_content = pub_text.find_parent(['div', 'section'])

            if view_content:
                print(f"  [+] Container trovato: {view_content.name}.{'.'.join(view_content.get('class', []))}")

                # METODO 1: Articles node--type-publication dentro container
                articles = view_content.find_all('article', class_='node--type-publication')
                if articles:
                    print(f"  [+] Metodo 1: {len(articles)} articles")
                    results_found = True

                    for article in articles:
                        title_link = article.find('h2', class_='node__title') or article.find('h2') or article.find('h3')
                        if title_link:
                            a_tag = title_link.find('a')
                            if a_tag and a_tag.get('href'):
                                href = a_tag['href']
                                if href.startswith('/'):
                                    full_url = f"https://osha.europa.eu{href}"
                                else:
                                    full_url = href

                                if full_url not in seen_urls:
                                    title = a_tag.text.strip()
                                    page_pubs.append({
                                        'titolo': title,
                                        'url': full_url
                                    })
                                    seen_urls.add(full_url)

                # METODO 2: Views-row dentro container
                if not results_found:
                    rows = view_content.find_all('div', class_='views-row')
                    pattern = re.compile(r'/en/publications/[a-z0-9-]+')

                    print(f"  [+] Metodo 2: {len(rows)} views-row")
                    results_found = bool(rows)

                    for row in rows:
                        a_tag = row.find('a', href=pattern)
                        if a_tag:
                            href = a_tag['href']
                            if href.startswith('/'):
                                full_url = f"https://osha.europa.eu{href}"
                            else:
                                full_url = href

                            if full_url not in seen_urls:
                                title = a_tag.text.strip()
                                if len(title) < 5:  # Ridotto threshold
                                    heading = row.find(['h2', 'h3'])
                                    if heading:
                                        title = heading.text.strip()

                                if title and len(title) >= 5:
                                    page_pubs.append({
                                        'titolo': title,
                                        'url': full_url
                                    })
                                    seen_urls.add(full_url)

                # METODO 3: Headings con links dentro container
                if not results_found or not page_pubs:
                    pattern = re.compile(r'/en/publications/[a-z0-9-]+')
                    headings = view_content.find_all(['h2', 'h3'])  # Cerca headings
                    print(f"  [+] Metodo 3: {len(headings)} headings in view_content")

                    for heading in headings:
                        a_tag = heading.find('a', href=pattern)
                        if a_tag:
                            href = a_tag['href']
                            if href.startswith('/'):
                                full_url = f"https://osha.europa.eu{href}"
                            else:
                                full_url = href

                            if full_url not in seen_urls:
                                title = a_tag.text.strip()
                                if title:  # Rimuovi check len, titles sono lunghi
                                    page_pubs.append({
                                        'titolo': title,
                                        'url': full_url
                                    })
                                    seen_urls.add(full_url)

                    if page_pubs:
                        results_found = True
                        print(f"  [+] Trovati {len(page_pubs)} via headings")

            if not results_found:
                print(f"  [!] Nessun risultato nella lista principale - fallback globale")
                # Fallback: tutti links con pattern nel soup (esclude raccomandate manualmente se noto)
                pattern = re.compile(r'/en/publications/[a-z0-9-]+')
                all_links = soup.find_all('a', href=pattern)
                print(f"  [FALLBACK] {len(all_links)} link totali")
                for a in all_links[:3]:
                    print(f"    Debug: {a['href']} - '{a.text.strip()}' (len: {len(a.text.strip())})")
                # Filtra escludendo se text == 'See more' o short
                for a in all_links:
                    title = a.text.strip()
                    if len(title) > 10 and 'see more' not in title.lower():
                        full_url = f"https://osha.europa.eu{a['href']}" if a['href'].startswith('/') else a['href']
                        if full_url not in seen_urls:
                            page_pubs.append({'titolo': title, 'url': full_url})
                            seen_urls.add(full_url)
                if page_pubs:
                    results_found = True

            if page_pubs:
                print(f"  [FOUND] {len(page_pubs)} nuove pubblicazioni dalla lista principale")
                for pub in page_pubs:
                    print(f"    - {pub['titolo'][:75]}...")
                publications.extend(page_pubs)
            else:
                print(f"  [!] Ancora 0 - verifica manualmente")
                break  # Break solo se 0 (non <5)

        except requests.exceptions.RequestException as e:
            print(f"  [!] Errore: {e}")
            break

    print(f"\n[RESULT] Totale: {len(publications)} pubblicazioni trovate dalla lista principale")
    return publications

# PDF PROCESSING

def download_pdf_osha(pdf_url: str, output_path: Path) -> bool:

    # Scarica PDF da URL
    try:
        headers = {'User-Agent': OSHAConfig.USER_AGENT}
        response = requests.get(
            pdf_url,
            headers=headers,
            timeout=OSHAConfig.TIMEOUT,
            stream=True
        )
        response.raise_for_status()

        with open(output_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)

        return output_path.exists() and output_path.stat().st_size > 0
    except Exception as e:
        print(f"[!] Errore download PDF: {e}")
        return False

# IMAGE EXPORT

def export_images_from_document(doc, doc_id: str) -> List[Dict[str, Any]]:

    # Esporta immagini da documento Docling - IDENTICA A INAIL
    images_dir = OSHAConfig.IMAGES_DIR / doc_id
    images_dir.mkdir(parents=True, exist_ok=True)
    exported_images = []

    try:
        from docling_core.types.doc import PictureItem
        if hasattr(doc, 'iterate_items'):
            for element, _level in doc.iterate_items():
                if isinstance(element, PictureItem):
                    picture_counter = len(exported_images) + 1
                    img_filename = f"figure_{picture_counter}.png"
                    img_path = images_dir / img_filename

                    try:
                        pil_image = element.get_image(doc)
                        pil_image.save(str(img_path), "PNG")
                        exported_images.append({
                            'path': str(img_path),
                            'filename': img_filename,
                            'caption': getattr(element, 'caption', 'N/A'),
                            'position': len(exported_images),
                            'vlm_description': None
                        })
                        print(f"  [+] {img_filename}")
                    except Exception as e:
                        print(f"  [!] Errore figura: {e}")

        print(f"[OK] {len(exported_images)} immagini esportate")
    except Exception as e:
        print(f"[ERROR] Export immagini: {e}")

    return exported_images

# VLM DESCRIPTIONS

def add_vlm_descriptions_to_images(exported_images: List[Dict], doc_id: str) -> List[Dict]:
    # Aggiunge descrizioni VLM alle immagini
    if not exported_images or not OSHAConfig.VLM_ENABLED:
        return exported_images

    try:
        from transformers import AutoProcessor, AutoModelForVision2Seq
        from PIL import Image
        import torch

        print(f"\n[VLM] Caricamento {OSHAConfig.VLM_MODEL}...")

        processor = AutoProcessor.from_pretrained(OSHAConfig.VLM_MODEL, trust_remote_code=True)
        model = AutoModelForVision2Seq.from_pretrained(
            OSHAConfig.VLM_MODEL,
            torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
            device_map="auto",
            trust_remote_code=True
        )

        for idx, img_data in enumerate(exported_images, 1):
            try:
                print(f"  [{idx}/{len(exported_images)}] {img_data['filename']}")
                image = Image.open(img_data['path']).convert('RGB')

                messages = [{
                    "role": "user",
                    "content": [
                        {"type": "image"},
                        {"type": "text", "text": OSHAConfig.VLM_PROMPT}
                    ]
                }]

                prompt = processor.apply_chat_template(messages, add_generation_prompt=True)
                inputs = processor(text=prompt, images=[image], return_tensors="pt").to(model.device)

                with torch.no_grad():
                    outputs = model.generate(**inputs, max_new_tokens=300, do_sample=False)

                full_output = processor.decode(outputs[0], skip_special_tokens=True)
                description = full_output.split("Assistant:")[-1].strip() if "Assistant:" in full_output else full_output.strip()

                img_data['vlm_description'] = description

                # Salva come .txt
                img_path = Path(img_data['path'])
                txt_path = img_path.with_suffix('.txt')

                with open(txt_path, 'w', encoding='utf-8') as f:
                    f.write("="*80 + "\n")
                    f.write(f"VLM DESCRIPTION - {img_data['filename']}\n")
                    f.write("="*80 + "\n\n")
                    f.write("IMAGE METADATA:\n")
                    f.write(f"  - Filename: {img_data['filename']}\n")
                    f.write(f"  - Caption: {img_data.get('caption', 'N/A')}\n")
                    f.write(f"  - Position: {img_data.get('position', 'N/A')}\n")
                    f.write(f"  - Model: {OSHAConfig.VLM_MODEL}\n")
                    f.write(f"  - Timestamp: {datetime.now().isoformat()}\n\n")
                    f.write("VLM ANALYSIS:\n")
                    f.write("-"*80 + "\n")
                    f.write(description)
                    f.write("\n" + "-"*80 + "\n")

                img_data['vlm_description_file'] = str(txt_path)
                print(f"    ✓ {description[:60]}...")

            except Exception as e:
                print(f"    ✗ {e}")
                img_data['vlm_description'] = None
                img_data['vlm_description_file'] = None

        del model, processor
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        success = sum(1 for img in exported_images if img.get('vlm_description'))
        print(f"[VLM] Completato: {success}/{len(exported_images)}\n")

    except Exception as e:
        print(f"[ERROR] VLM fallito: {e}")

    return exported_images

# SCRAPING SINGOLA PUBBLICAZIONE

def scrape_osha_publication(
    publication_url: str,
    converter,
    save_pdf: bool = True,
    enable_vlm: Optional[bool] = None
) -> Dict[str, Any]:

    # Scrape singola pubblicazione OSHA - ARRICCHITO CON ENHANCED TABLES
    use_vlm = enable_vlm if enable_vlm is not None else OSHAConfig.VLM_ENABLED

    print(f"\n{'='*80}")
    print(f"SCRAPING PUBBLICAZIONE")
    print(f"{'='*80}\n")

    scraping_metadata = {
        'url': publication_url,
        'timestamp': datetime.now().isoformat(),
        'scraper_version': '5.3_ENHANCED_TABLES',  # Update per Enhanced Tables
        'docling_used': True,
        'vlm_enabled': use_vlm
    }

    try:
        headers = {'User-Agent': OSHAConfig.USER_AGENT}
        response = requests.get(publication_url, headers=headers, timeout=OSHAConfig.TIMEOUT)
        response.raise_for_status()

        page = BeautifulSoup(response.content, 'lxml')

        # Estrai metadati (invariato)
        title_elem = page.find('h1')
        title = title_elem.text.strip() if title_elem else 'N/A'

        # Description (salviamo come abstract per allineamento)
        descr_blocks = page.find_all(id=re.compile('^tmgmt-'))
        description = ' '.join(p.get_text(strip=True, separator=' ') for p in descr_blocks)
        description = re.sub(r'\s+', ' ', description.replace('\xa0', ' ')).strip()

        # Data pubblicazione
        date_elem = page.find('p', class_='datetime-style')
        data_pubblicazione = date_elem.text.strip() if date_elem else 'N/A'

        # PDF URL
        link_pdf_elem = page.find('div', class_='download-pdf')
        pdf_url = None
        if link_pdf_elem and link_pdf_elem.find('a'):
            pdf_url = link_pdf_elem.find('a')['href']

        # KEYWORDS - Salvate SEPARATAMENTE per arricchimento successivo
        keywords_elem = page.find('ul', class_='field__items')
        keywords = [kw.strip() for kw in keywords_elem.text.strip().split('\n')] if keywords_elem else []

        # Salva keywords in file separato
        if keywords:
            safe_filename = re.sub(r'[^\w\-_.]', '_', title[:50])
            keywords_path = OSHAConfig.KEYWORDS_DIR / f"{safe_filename}_keywords.json"
            with open(keywords_path, 'w', encoding='utf-8') as f:
                json.dump({
                    'url': publication_url,
                    'title': title,
                    'keywords': keywords
                }, f, ensure_ascii=False, indent=2)

        print(f"[+] {title[:60]}...")
        print(f"[+] Data: {data_pubblicazione}")

        # PDF Processing - MODIFICATO
        pdf_data = None
        pdf_local_path = None

        if pdf_url:
            safe_filename = re.sub(r'[^\w\-_.]', '_', title[:50]) + '.pdf'
            pdf_local_path = OSHAConfig.PDF_DIR / safe_filename
            doc_id = safe_filename.replace('.pdf', '')

            if download_pdf_osha(pdf_url, pdf_local_path):
                print(f"[INFO] Processing PDF con enhanced table extraction...")

                result = converter.convert(str(pdf_local_path))
                doc = result.document

                markdown_text = doc.export_to_markdown()
                plain_text = doc.export_to_text()

                # CHIAMA ENHANCED PARSER
                structure_info = analyze_document_structure_enhanced(doc)

                exported_images = export_images_from_document(doc, doc_id)

                if use_vlm and exported_images:
                    exported_images = add_vlm_descriptions_to_images(exported_images, doc_id)
                    for idx, fig_info in enumerate(structure_info.get('figures', [])):
                        if idx < len(exported_images):
                            vlm_desc = exported_images[idx].get('vlm_description')
                            if vlm_desc:
                                fig_info['vlm_description'] = vlm_desc

                # CHIAMA ENHANCED TABLE EXPORT
                exported_tables = export_tables_to_files_enhanced(
                    structure_info['tables'],
                    doc_id,
                    OSHAConfig.TABLES_DIR
                )

                pdf_data = {
                    'markdown_content': markdown_text,
                    'plain_text': plain_text,
                    'num_pages': len(doc.pages) if hasattr(doc, 'pages') else 'N/A',
                    'num_tables': structure_info['num_tables'],
                    'num_figures': structure_info['num_figures'],
                    'num_headings': structure_info['num_headings'],
                    'headings': structure_info['headings'],
                    'tables': structure_info['tables'],
                    'figures': structure_info['figures'],
                    'exported_images': exported_images,
                    'exported_tables': exported_tables
                }

                print(f"[OK] {pdf_data['num_pages']} pag | {pdf_data['num_tables']} tab (enhanced) | {pdf_data['num_figures']} fig")

                if not save_pdf:
                    pdf_local_path.unlink()
                    pdf_local_path = None

        # STRUTTURA JSON IDENTICA A INAIL
        return {
            'scraping_metadata': scraping_metadata,
            'web_metadata': {
                'title': title,
                'abstract': description,  # description → abstract
                'data_pubblicazione': data_pubblicazione,  # Stesso nome di INAIL
                'pdf_url': pdf_url,
                'pdf_local_path': str(pdf_local_path) if pdf_local_path else None
            },
            'document_content': pdf_data,
            'status': 'success',
            'has_pdf': pdf_url is not None,
            'pdf_processed': pdf_data is not None
        }

    except Exception as e:
        print(f"[ERROR] {e}")
        return {
            'scraping_metadata': scraping_metadata,
            'status': 'error',
            'error_message': str(e)
        }

# SAVE & TRACKING

def save_to_json(data: Dict[str, Any], output_name: Optional[str] = None) -> Path:

    # Salva dati in JSON con verifica - IDENTICO A INAIL
    try:
        if output_name is None:
            title = data.get('web_metadata', {}).get('title', 'unknown')
            safe_title = re.sub(r'[^\w\-_.]', '_', title[:50])
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output_name = f"{safe_title}_{timestamp}.json"

        output_path = OSHAConfig.JSON_DIR / output_name

        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        if output_path.exists():
            size_kb = output_path.stat().st_size / 1024
            print(f"  JSON: {output_name} ({size_kb:.1f} KB)")
            return output_path
        else:
            print(f"  ERRORE: File non creato!")
            return None

    except Exception as e:
        print(f"  ERRORE SALVATAGGIO: {e}")
        return None


def load_already_scraped_urls() -> set:

    # Carica URL già processati dai JSON
    scraped_urls = set()

    json_dir = OSHAConfig.JSON_DIR
    if not json_dir.exists():
        return scraped_urls

    json_files = list(json_dir.glob("*.json"))

    for json_file in json_files:
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)

            docs = data if isinstance(data, list) else [data]

            for doc in docs:
                url = doc.get('scraping_metadata', {}).get('url')
                if url:
                    scraped_urls.add(url)
        except:
            continue

    return scraped_urls

# BATCH SCRAPING INCREMENTALE

def batch_scrape_osha_publications_incremental(
    converter,
    start_page: int = 0,
    end_page: int = 4,
    max_documents: Optional[int] = None,
    enable_vlm: bool = False,
    save_pdfs: bool = False,
    delay_between_docs: int = 4
) -> List[Dict[str, Any]]:

    # Batch scraping incrementale OSHA - MODIFICATO: senza query, lista generale ordinata per data
    # 1) Carica URL già processati
    already_scraped = load_already_scraped_urls()

    print(f"\n{'='*80}")
    print(f"SCRAPING INCREMENTALE OSHA (LISTA PRINCIPALE, ORDINATA PER DATA)")
    print(f"{'='*80}")
    print(f"Documenti già nel database: {len(already_scraped)}")
    print(f"Lingua: en (default)")
    print(f"Pagine: {start_page} → {end_page}")
    print(f"{'='*80}\n")

    # 2) Costruisci search URL base (senza query, ordinato per data DESC)
    search_url = build_osha_search_url(query="", lang="en")

    # 3) Estrai link
    publication_links = get_osha_publication_links_with_range(
        search_url,
        start_page=start_page,
        end_page=end_page
    )

    if not publication_links:
        print("[WARNING] Nessuna pubblicazione trovata nella lista principale")
        return []

    # 4) Filtra SOLO nuovi
    new_links = [pub for pub in publication_links if pub['url'] not in already_scraped]

    print(f"\n{'='*80}")
    print(f"FILTRO DOCUMENTI")
    print(f"{'='*80}")
    print(f"Trovati: {len(publication_links)}")
    print(f"NUOVI: {len(new_links)}")
    print(f"GIÀ PROCESSATI (skip): {len(publication_links) - len(new_links)}")
    print(f"{'='*80}\n")

    if not new_links:
        print("✓ Nessun nuovo documento in questo range!")
        print(f"  Prova ad aumentare il range (es: {end_page+1}-{end_page+5})")
        return []

    # Mostra lista nuovi
    print("📋 NUOVE PUBBLICAZIONI DA SCARICARE (dalla lista principale):")
    for i, pub in enumerate(new_links[:10], 1):
        print(f"  {i}. {pub['titolo'][:70]}...")
    if len(new_links) > 10:
        print(f"  ... e altre {len(new_links) - 10}\n")
    else:
        print()

    # Limite documenti
    if max_documents:
        new_links = new_links[:max_documents]
        print(f"[INFO] Limitato a {max_documents} nuovi documenti\n")

    # 5) Scraping
    results = []
    failed = []

    print(f"{'='*80}")
    print(f"SCRAPING {len(new_links)} NUOVI DOCUMENTI")
    print(f"{'='*80}\n")

    for idx, pub in enumerate(new_links, 1):
        print(f"\n[{idx}/{len(new_links)}] {pub['titolo'][:60]}...")

        try:
            result = scrape_osha_publication(
                publication_url=pub['url'],
                converter=converter,
                save_pdf=save_pdfs,
                enable_vlm=enable_vlm
            )

            if result['status'] == 'success':
                json_path = save_to_json(result)

                if json_path and json_path.exists():
                    results.append(result)
                    print(f"  ✓ SALVATO")
                else:
                    print(f"  ✗ Processato ma NON salvato")
                    failed.append({
                        'url': pub['url'],
                        'title': pub['titolo'],
                        'error': 'JSON save failed'
                    })
            else:
                failed.append({
                    'url': pub['url'],
                    'title': pub['titolo'],
                    'error': result.get('error_message', 'Unknown')
                })
                print(f"  ✗ FAIL")

        except KeyboardInterrupt:
            print(f"\nINTERRUZIONE - Salvati: {len(results)}")
            break

        except Exception as e:
            print(f"  ✗ Eccezione: {str(e)[:80]}")
            failed.append({'url': pub['url'], 'title': pub['titolo'], 'error': str(e)})

        # Delay
        if idx < len(new_links):
            delay = random.uniform(delay_between_docs, delay_between_docs + 2)
            time.sleep(delay)

    # Riepilogo
    print(f"\n{'='*80}")
    print(f"COMPLETATO")
    print(f"{'='*80}")
    print(f"Nuovi salvati: {len(results)}")
    print(f"Falliti: {len(failed)}")
    print(f"Totale database: {len(already_scraped) + len(results)}")
    print(f"Path: {OSHAConfig.OUTPUT_DIR}")
    print(f"{'='*80}\n")

    if failed:
        print("\nDOCUMENTI FALLITI:")
        for f in failed[:5]:
            print(f"  • {f['title'][:50]}: {f['error']}")
        if len(failed) > 5:
            print(f"  ... e altri {len(failed)-5}")

    return results

# UTILITIES

def list_directory_contents():

    # Mostra statistiche directory
    json_dir = OSHAConfig.JSON_DIR
    pdf_dir = OSHAConfig.PDF_DIR
    images_dir = OSHAConfig.IMAGES_DIR
    tables_dir = OSHAConfig.TABLES_DIR
    keywords_dir = OSHAConfig.KEYWORDS_DIR

    print(f"\n{'='*80}")
    print("STATISTICHE DIRECTORY OSHA")
    print(f"{'='*80}\n")

    if json_dir.exists():
        json_files = list(json_dir.glob("*.json"))
        total_size = sum(f.stat().st_size for f in json_files) / (1024*1024)
        print(f"JSON: {len(json_files)} file ({total_size:.1f} MB)")

        if json_files:
            recent = sorted(json_files, key=lambda x: x.stat().st_mtime, reverse=True)[:3]
            print("   Ultimi 3:")
            for f in recent:
                print(f"     • {f.name}")

    if pdf_dir.exists():
        pdf_files = list(pdf_dir.glob("*.pdf"))
        total_size = sum(f.stat().st_size for f in pdf_files) / (1024*1024)
        print(f"\nPDF: {len(pdf_files)} file ({total_size:.1f} MB)")

    if images_dir.exists():
        image_folders = [d for d in images_dir.iterdir() if d.is_dir()]
        total_images = sum(len(list(d.glob("*.png"))) for d in image_folders)
        total_txt = sum(len(list(d.glob("*.txt"))) for d in image_folders)
        print(f"\nImmagini: {total_images} PNG + {total_txt} descrizioni VLM")
        print(f"   in {len(image_folders)} documenti")

    if tables_dir.exists():
        table_folders = [d for d in tables_dir.iterdir() if d.is_dir()]
        total_tables = sum(len(list(d.glob("*.txt"))) for d in table_folders)
        print(f"\nTabelle: {total_tables} file (enhanced parsing)")
        print(f"   in {len(table_folders)} documenti")

    if keywords_dir.exists():
        keyword_files = list(keywords_dir.glob("*_keywords.json"))
        print(f"\nKeywords: {len(keyword_files)} file")

    print(f"\n{'='*80}\n")


def verify_json_files():
    """Verifica integrità file JSON"""
    json_dir = OSHAConfig.JSON_DIR
    if not json_dir.exists():
        print("Directory JSON non esiste")
        return

    json_files = list(json_dir.glob("*.json"))

    print(f"\n{'='*80}")
    print(f"VERIFICA {len(json_files)} FILE JSON")
    print(f"{'='*80}\n")

    valid = 0
    invalid = []

    for json_file in json_files:
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)

            # Verifica struttura INAIL-compatibile
            required_keys = ['scraping_metadata', 'web_metadata', 'status']
            if all(key in data for key in required_keys):
                # Verifica campi web_metadata
                web_meta = data['web_metadata']
                if 'title' in web_meta and 'abstract' in web_meta and 'data_pubblicazione' in web_meta:
                    valid += 1
                else:
                    invalid.append(f"{json_file.name} (missing web_metadata fields)")
            else:
                invalid.append(f"{json_file.name} (missing required keys)")
        except Exception as e:
            invalid.append(f"{json_file.name} ({str(e)[:30]})")

    print(f"Validi (INAIL-compatible): {valid}")
    print(f"Invalidi: {len(invalid)}")

    if invalid:
        print("\nFile con problemi:")
        for f in invalid[:10]:
            print(f"  • {f}")

    print(f"\n{'='*80}\n")

# MAIN

def main():
    print("\n" + "="*80)
    print("OSHA SCRAPER")
    print("="*80)
    print("\nFEATURES:")
    print("   • Range pagine personalizzabile")
    print("   • Skip documenti già processati")
    print("   • Keywords salvate separatamente")
    print("   • VLM + Docling processing")
    print("   • Enhanced Table Parser (caption, headers, content pulito, type classification)\n")

    # STEP 1: Monta Drive (se Colab)
    print("[STEP 1] Montaggio Google Drive...")
    mount_google_drive()

    # STEP 2: Setup
    print("[STEP 2] Setup directories...")
    OSHAConfig.setup_directories()

    print("\n[VERIFICA] Controllo path...")
    if not OSHAConfig.verify_directories():
        print("Alcune directory non esistono!")
        return None

    # STEP 3: Statistiche
    print("\n[STEP 3] Caricamento statistiche...")
    already_scraped = load_already_scraped_urls()
    print(f"Documenti già processati: {len(already_scraped)}\n")

    # STEP 4: Docling
    print("[STEP 4] Inizializzazione Docling...")
    converter = initialize_docling_converter()

    # STEP 5: Menu
    print("=" * 80)
    print("MODALITÀ:")
    print("=" * 80)
    print("1. Scraping incrementale (lista principale, range pagine)")
    print("2. Statistiche directory")
    print("3. Verifica file JSON")
    print("=" * 80 + "\n")

    choice = input("Scegli (1-3, default 1): ").strip() or "1"

    if choice == "2":
        list_directory_contents()
        return None

    if choice == "3":
        verify_json_files()
        return None

    # CONFIGURAZIONE SCRAPING - MODIFICATA: Solo range e max docs
    print("\n[SETUP] Configurazione scraping (lista principale EN, ordinata per data)\n")

    # Range pagine (OSHA usa 0-indexed)
    print(f"Suggerimento: Hai già {len(already_scraped)} documenti")
    print(f"   Inizia da page=0 per i più recenti, o da una pagina alta (es. 150) per continuare\n")

    try:
        start_page_input = input("Pagina di INIZIO (default 0): ").strip()
        start_page = int(start_page_input) if start_page_input else 0
    except:
        start_page = 0

    num_pages_input = input("Numero di PAGINE da scansionare (default 5, min 1): ").strip()
    try:
        num_pages = int(num_pages_input) if num_pages_input else 5
        if num_pages < 1:
            num_pages = 1
            print("  [INFO] Impostato min=1")
    except:
        num_pages = 5
    end_page = start_page + num_pages - 1

    # Validazione finale (no +4 force)
    if start_page < 0:
        start_page = 0

    max_docs_input = input(f"\nLimite nuovi docs (Enter = tutti): ").strip()
    max_docs = int(max_docs_input) if max_docs_input else None

    vlm_input = input("VLM? (y/n, default: y): ").strip().lower()
    enable_vlm = (vlm_input != 'n')

    pdf_input = input("Salvare PDF? (y/n, default: n): ").strip().lower()
    save_pdfs = (pdf_input == 'y')

    # Riepilogo
    print(f"\n{'='*80}")
    print("RIEPILOGO:")
    print(f"{'='*80}")
    print(f"Lingua: en (lista principale)")
    print(f"Range pagine: {start_page} → {end_page} ({num_pages} pagine)")
    print(f"Nuovi docs max: {max_docs if max_docs else '(tutti trovati)'}")
    print(f"VLM: {'ON' if enable_vlm else 'OFF'}")
    print(f"Salva PDF: {'SI' if save_pdfs else 'NO (solo metadati)'}")
    print(f"Già nel database: {len(already_scraped)} documenti")
    print(f"Output: {OSHAConfig.JSON_DIR}")
    print(f"{'='*80}\n")

    confirm = input("Procedere? (y/n): ").strip().lower()
    if confirm != 'y':
        print("ANNULLATO")
        return None

    # ESEGUI SCRAPING
    results = batch_scrape_osha_publications_incremental(
        converter=converter,
        start_page=start_page,
        end_page=end_page,
        max_documents=max_docs,
        enable_vlm=enable_vlm,
        save_pdfs=save_pdfs,
        delay_between_docs=4
    )

    # Statistiche finali dentro main
    print("\n" + "="*80)
    print("SCRAPING TERMINATO")
    print("="*80)

    if results:
        print(f"✓ Nuovi documenti salvati: {len(results)}")

    total_docs = len(load_already_scraped_urls())
    print(f"Documenti totali nel database: {total_docs}")
    print(f"Path: {OSHAConfig.OUTPUT_DIR}")

    print("\n" + "="*80)
    print("STATISTICHE FINALI:")
    print("="*80)
    list_directory_contents()

    print("="*80 + "\n")

    print("SUGGERIMENTI:")
    print(f"   • Prossimo range: pagina {end_page + 1} → {end_page + num_pages}")
    print(f"   • Documenti totali: {total_docs}")
    print(f"   • Keywords salvate in: {OSHAConfig.KEYWORDS_DIR}")
    print(f"   • Per tabelle: Controlla .txt in tables/ – ora con Enhanced Parsing")
    print(f"   • Enhanced Tables: Caption/context-aware, headers, formatted content\n")

    return results

# ESECUZIONE

if __name__ == "__main__":
    results = main()