# -*- coding: utf-8 -*-
"""tf_idf_embedgemma_hpc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K4o8J6b5ijkQ9W1VE2XP4AHFP4f1wUr5
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
INAIL Document Enrichment System - HPC Version
Adapted for /mnt/beegfs/proj/dss.dmaia/INAILProj
"""

import json
import re
import logging
import numpy as np
import os
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple, Set
from datetime import datetime
from collections import Counter, defaultdict
import traceback

# Import principali
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import AgglomerativeClustering
import networkx as nx
from sentence_transformers import SentenceTransformer

# ============================================================================
# CONFIGURAZIONE HPC
# ============================================================================

class Config:
    # PERCORSI HPC
    HPC_BASE_DIR = Path("/mnt/beegfs/proj/dss.dmaia/INAILProj")
    JSON_DIR = HPC_BASE_DIR / "json"
    ENRICHED_DIR = HPC_BASE_DIR / "enriched_json"
    LOG_DIR = HPC_BASE_DIR / "logs"
    GRAPH_DIR = HPC_BASE_DIR / "graphs"

    # MODELLI LOCALI SU HPC
    LOCAL_EMBEDDING_MODEL_PATH = HPC_BASE_DIR / "models" / "EmbeddingGemma_Offline"
    SENT2VEC_MODEL_PATH = HPC_BASE_DIR / "models" / "sent2vec_wiki_unigrams.bin"

    # CONFIGURAZIONE EMBEDDING
    USE_EMBEDDING_GEMMA = True
    USE_LOCAL_HPC_MODEL = True
    FALLBACK_MODEL = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"

    # DATI DOMINIO
    DOCUMENT_CATEGORIES = [
        "Rischio chimico e cancerogeno", "Rischio biologico",
        "Rischio fisico (rumore, vibrazioni, radiazioni)",
        "Prevenzione incendi ed esplosioni", "Sicurezza macchine e attrezzature",
        "Edilizia e cantieri", "Agricoltura e silvicoltura", "Trasporti e logistica",
        "Settore sanitario", "DPI e dispositivi di protezione",
        "Formazione e addestramento", "Sorveglianza sanitaria",
        "Normativa e adempimenti", "Valutazione e gestione del rischio",
        "Infortuni e malattie professionali", "Altro"
    ]

    CATEGORY_TERMS = {
        "Rischio chimico e cancerogeno": ["cancerogeni", "mutageni", "chimici", "sostanze",
            "agenti chimici", "esposizione", "classificazione", "amianto", "fibre", "polveri minerali"],
        "Rischio biologico": ["biologici", "virus", "batteri", "contaminazione", "agenti biologici"],
        "Rischio fisico (rumore, vibrazioni, radiazioni)": ["rumore", "vibrazioni", "radiazioni",
            "temperature", "fisici"],
        "Prevenzione incendi ed esplosioni": ["incendi", "esplosioni", "antincendio", "emergenza", "evacuazione"],
        "Sicurezza macchine e attrezzature": ["macchine", "attrezzature", "impianti", "manutenzione", "utilizzo"],
        "Edilizia e cantieri": ["cantieri", "edilizia", "costruzioni", "ponteggi", "scavi", "demolizioni"],
        "Agricoltura e silvicoltura": ["agricoltura", "forestali", "agricoltori", "rurale", "coltivazioni", "potatori"],
        "Trasporti e logistica": ["trasporti", "autotrasporto", "conducenti", "veicoli", "logistica", "alcol", "guida"],
        "Settore sanitario": ["sanitario", "ospedale", "infermieri", "medici", "pazienti", "clinica"],
        "DPI e dispositivi di protezione": ["dpi", "dispositivi", "protezione individuale", "respiratori", "maschere"],
        "Formazione e addestramento": ["formazione", "addestramento", "corsi", "certificazione", "istruzione"],
        "Sorveglianza sanitaria": ["sorveglianza", "sanitaria", "medica", "visite", "controlli", "accertamenti"],
        "Valutazione e gestione del rischio": ["valutazione", "gestione", "analisi", "misurazione", "identificazione"],
        "Infortuni e malattie professionali": ["infortuni", "incidenti", "malattie professionali", "statistiche", "cause"]
    }

    KNOWN_PROFESSIONS = [
        "Operai edili", "Carpentieri", "Muratori", "Ponteggiatori", "Elettricisti", "Idraulici", "Saldatori",
        "Meccanici industriali", "Operatori macchine utensili", "Manutentori", "Agricoltori", "Operatori forestali",
        "Potatori", "Infermieri", "Medici", "OSS", "Tecnici di laboratorio", "Radiologi", "Operatori sanitari",
        "Autisti professionali", "Magazzinieri", "Mulettisti", "Tecnici della prevenzione", "RSPP", "ASPP",
        "HSE Manager", "Coordinatori per la sicurezza", "RLS", "Preposti alla sicurezza", "Chimici", "Biologi",
        "Tecnici di laboratorio chimico", "Lavoratori esposti ad agenti chimici pericolosi",
        "Lavoratori esposti ad agenti cancerogeni o mutageni", "Lavoratori esposti ad agenti biologici",
        "Lavoratori esposti a polveri e fibre minerali", "Lavoratori esposti a rumore e vibrazioni",
        "Lavoratori in ambienti confinati", "Lavoratori in quota", "Addetti antincendio",
        "Lavoratori generici", "Tutti i lavoratori"
    ]

    PROFESSION_BLACKLIST = {"Addetti antincendio", "Lavoratori generici", "Tutti i lavoratori"}

    DOMAIN_TERMS = {
        'cancerogeni', 'mutageni', 'esposizione', 'prevenzione', 'protezione', 'valutazione', 'sorveglianza',
        'sanitaria', 'dispositivi', 'respiratori', 'ventilazione', 'aspirazione', 'manipolazione', 'stoccaggio',
        'etichettatura', 'classificazione', 'schede', 'sicurezza', 'infortuni', 'malattie', 'professionali',
        'rischio', 'pericolo', 'normativa', 'adempimenti', 'obblighi', 'responsabilità', 'formazione',
        'addestramento', 'informazione', 'istruzioni', 'incendi', 'esplosioni', 'emergenza', 'evacuazione',
        'cantieri', 'ponteggi', 'scavi', 'demolizioni', 'macchine', 'attrezzature', 'impianti', 'manutenzione',
        'chimici', 'biologici', 'fisici', 'ergonomici', 'rumore', 'vibrazioni', 'radiazioni', 'temperature',
        'elettrico', 'meccanico', 'caduta', 'schiacciamento', 'amianto', 'silice', 'piombo', 'solventi', 'polveri'
    }

    MIN_TEXT_LENGTH = 100
    PROFESSION_THRESHOLD = 0.55
    CATEGORY_THRESHOLD = 0.30

    # CONFIGURAZIONE BATCH
    BATCH_SIZE = 100  # Processa 100 documenti alla volta per monitoraggio
    SAVE_ALL_GRAPHS = True  # Salva tutti i grafi EmbedRank

    @classmethod
    def setup(cls):
        """Verifica e crea le directory necessarie su HPC"""
        if not cls.HPC_BASE_DIR.exists():
            print(f"❌ Directory base non trovata: {cls.HPC_BASE_DIR}")
            return False

        if not cls.JSON_DIR.exists():
            print(f"❌ Directory JSON non trovata: {cls.JSON_DIR}")
            return False

        json_files = list(cls.JSON_DIR.glob("*.json"))
        if len(json_files) == 0:
            print("❌ Nessun file JSON trovato")
            return False

        print(f"✓ Trovati {len(json_files)} file JSON")

        # Crea directory output
        for d in [cls.ENRICHED_DIR, cls.LOG_DIR, cls.GRAPH_DIR]:
            d.mkdir(exist_ok=True, parents=True)
            print(f"✓ Directory pronta: {d}")

        # Verifica modello locale
        if cls.USE_LOCAL_HPC_MODEL:
            if not cls.LOCAL_EMBEDDING_MODEL_PATH.exists():
                print(f"⚠️  Modello locale non trovato: {cls.LOCAL_EMBEDDING_MODEL_PATH}")
                print(f"   Devi copiare il modello da Drive a questo percorso")
                print(f"   Comando suggerito:")
                print(f"   scp -r /path/to/drive/EmbeddingGemma_Offline username@hpc:{cls.LOCAL_EMBEDDING_MODEL_PATH}")
                return False
            else:
                print(f"✓ Modello EmbeddingGemma trovato: {cls.LOCAL_EMBEDDING_MODEL_PATH}")

        return True

# ============================================================================
# EMBEDDING MODEL LOADER (HPC)
# ============================================================================

def load_embedding_model_hpc() -> Optional[SentenceTransformer]:
    """Carica il modello embedding su HPC (solo locale)"""

    local_path = Config.LOCAL_EMBEDDING_MODEL_PATH

    if Config.USE_LOCAL_HPC_MODEL and local_path.exists():
        print(f"\n[Embedding Model] Caricamento da: {local_path}")
        try:
            model = SentenceTransformer(str(local_path))
            print(f"✓ Modello EmbeddingGemma caricato con successo")
            print(f"  Device: {model.device}")
            return model
        except Exception as e:
            print(f"❌ Errore caricamento modello locale: {e}")
            print(f"  Tentativo fallback...")

    # FALLBACK: BERT Multilingue
    print(f"\n[Embedding Model] Fallback al modello: {Config.FALLBACK_MODEL}")
    try:
        model = SentenceTransformer(Config.FALLBACK_MODEL)
        print(f"✓ Fallback model caricato - Device: {model.device}")
        return model
    except Exception as e:
        print(f"❌ Errore caricamento fallback: {e}")
        return None

# ============================================================================
# LAW EXTRACTOR
# ============================================================================

class LawExtractor:
    PATTERNS = {
        'dlgs': [r'[Dd]\.?\s*[Ll]\.?\s*[Gg]\.?\s*[Ss]?\.?\s*(?:n\.?\s*)?(\d+)\s*[/\-°]\s*(\d{2,4})'],
        'dm': [r'[Dd]\.?\s*[Mm]\.?\s+(?:del\s+)?(\d{1,2})[/\-\s]+(\d{1,2})[/\-\s]+(\d{2,4})'],
        'legge': [r'[Ll]\.?\s*(?:n\.?\s*)?(\d+)\s*[/\-°]\s*(\d{2,4})'],
        'dpr': [r'[Dd]\.?\s*[Pp]\.?\s*[Rr]\.?\s*(?:n\.?\s*)?(\d+)\s*[/\-°]\s*(\d{2,4})'],
        'direttiva_ue': [r'[Dd]irettiva\s+(?:UE\s+)?(\d{4})\s*[/\-]\s*(\d+)'],
    }

    def __init__(self):
        self.compiled_patterns = {}
        for tipo, patterns in self.PATTERNS.items():
            self.compiled_patterns[tipo] = [re.compile(p, re.IGNORECASE) for p in patterns]

    def extract_with_confidence(self, text: str) -> Tuple[List[str], Dict[str, float]]:
        found_laws = []
        law_counts = Counter()

        for tipo, compiled_patterns in self.compiled_patterns.items():
            for pattern in compiled_patterns:
                for match in pattern.finditer(text):
                    normalized = self._normalize_law(tipo, match.groups())
                    if normalized:
                        found_laws.append(normalized)
                        law_counts[normalized] += 1

        unique_laws = list(dict.fromkeys(found_laws))[:20]
        confidence = self._calculate_confidence(unique_laws, law_counts)

        return unique_laws, confidence

    def _normalize_law(self, tipo: str, match: tuple) -> Optional[str]:
        try:
            if tipo == 'dlgs':
                return f"D.Lgs. {match[0]}/{self._normalize_year(match[1])}"
            elif tipo == 'dm' and len(match) == 3:
                return f"D.M. {match[0]}/{match[1]}/{self._normalize_year(match[2])}"
            elif tipo == 'legge':
                return f"Legge n. {match[0]}/{self._normalize_year(match[1])}"
            elif tipo == 'dpr':
                return f"D.P.R. {match[0]}/{self._normalize_year(match[1])}"
            elif tipo == 'direttiva_ue':
                return f"Direttiva UE {match[0]}/{match[1]}"
        except:
            return None

    def _normalize_year(self, year_str: str) -> str:
        year = int(year_str)
        return str(2000 + year if year < 50 else 1900 + year if year < 100 else year)

    def _calculate_confidence(self, laws: List[str], counts: Counter) -> Dict[str, float]:
        if not laws:
            return {'overall': 0.0, 'count': 0.0, 'coverage': 0.0, 'coherence': 0.0}

        count_score = min(1.0, len(laws) / 5.0)
        avg_mentions = np.mean([counts[law] for law in laws])
        coverage_score = min(1.0, avg_mentions / 3.0)

        years = []
        for law in laws:
            match = re.search(r'/(\d{4})', law)
            if match:
                years.append(int(match.group(1)))

        if len(years) > 1:
            year_std = np.std(years)
            coherence_score = max(0.0, 1.0 - year_std / 30.0)
        else:
            coherence_score = 0.7

        overall = 0.4 * count_score + 0.35 * coverage_score + 0.25 * coherence_score

        return {
            'overall': round(overall, 3),
            'count': round(count_score, 3),
            'coverage': round(coverage_score, 3),
            'coherence': round(coherence_score, 3)
        }

# ============================================================================
# DOMAIN-AWARE TF-IDF + EMBEDRANK
# ============================================================================

class DomainAwareTFIDFExtractor:
    def __init__(self, embedding_model: SentenceTransformer, domain_terms: Set[str]):
        self.embedding_model = embedding_model
        self.domain_terms = domain_terms
        self.stopwords = self._load_stopwords()

    def extract_keywords_with_confidence(
        self,
        document_text: str,
        top_n: int = 8,
        save_graph: bool = True,
        graph_path: Optional[Path] = None,
        doc_title: str = "Document"
    ) -> Tuple[List[str], Dict[str, Any], Optional[nx.Graph]]:

        tfidf_keywords = self._extract_tfidf_domain_aware(document_text)

        if not tfidf_keywords:
            return [], {'confidence': {'overall': 0.0}}, None

        embedrank_keywords, G = self._embed_rank(tfidf_keywords, document_text)

        final_keywords = self._combine_and_diversify(
            tfidf_keywords, embedrank_keywords, top_n
        )

        confidence = self._calculate_confidence(
            final_keywords, tfidf_keywords, embedrank_keywords, document_text, G
        )

        if save_graph and G and graph_path:
            embedrank_scores = dict(embedrank_keywords)
            self._save_graph(G, embedrank_scores, graph_path, doc_title)

        metadata = {
            'keywords': final_keywords,
            'tfidf_keywords': [kw for kw, _ in tfidf_keywords[:10]],
            'embedrank_keywords': [kw for kw, _ in embedrank_keywords[:10]],
            'confidence': confidence,
            'method': 'TF-IDF-DomainAware + EmbedRank'
        }

        return final_keywords, metadata, G

    def _extract_tfidf_domain_aware(self, text: str, top_n: int = 30) -> List[Tuple[str, float]]:
        text_clean = self._preprocess(text)

        if len(text_clean) < 50:
            return []

        try:
            vectorizer = TfidfVectorizer(
                max_features=100,
                ngram_range=(1, 3),
                stop_words=list(self.stopwords),
                min_df=1,
                lowercase=True,
                token_pattern=r'(?u)\b[a-zàèéìòù]{4,}\b'
            )

            tfidf_matrix = vectorizer.fit_transform([text_clean])
            feature_names = vectorizer.get_feature_names_out()
            scores = tfidf_matrix.toarray()[0]

            boosted_scores = []
            for i, term in enumerate(feature_names):
                score = scores[i]
                if any(domain_term in term for domain_term in self.domain_terms):
                    score *= 1.5
                boosted_scores.append((term, score))

            boosted_scores.sort(key=lambda x: x[1], reverse=True)
            return boosted_scores[:top_n]

        except:
            return []

    def _embed_rank(self, candidates: List[Tuple[str, float]], document_text: str) -> Tuple[List[Tuple[str, float]], nx.Graph]:
        if len(candidates) < 3:
            return candidates, nx.Graph()

        candidate_terms = [term for term, _ in candidates[:30]]

        doc_emb = self.embedding_model.encode(
            [document_text[:3000]],
            convert_to_numpy=True,
            show_progress_bar=False,
        )[0]

        term_embs = self.embedding_model.encode(
            candidate_terms,
            convert_to_numpy=True,
            show_progress_bar=False,
        )

        G = nx.Graph()

        for i, term_i in enumerate(candidate_terms):
            doc_sim = float(cosine_similarity([term_embs[i]], [doc_emb])[0][0])
            G.add_node(term_i, doc_similarity=doc_sim)

            for j in range(i + 1, len(candidate_terms)):
                term_sim = float(cosine_similarity([term_embs[i]], [term_embs[j]])[0][0])
                if term_sim > 0.3:
                    G.add_edge(candidate_terms[i], candidate_terms[j], weight=term_sim)

        if len(G.nodes()) == 0:
            return candidates, G

        try:
            pagerank_scores = nx.pagerank(G, alpha=0.85, max_iter=100, weight='weight')

            final_scores = []
            for term in candidate_terms:
                pr = pagerank_scores.get(term, 0)
                doc_sim = G.nodes[term].get('doc_similarity', 0)
                combined = 0.6 * pr + 0.4 * doc_sim
                final_scores.append((term, combined))

            final_scores.sort(key=lambda x: x[1], reverse=True)
            return final_scores, G

        except:
            return candidates, G

    def _combine_and_diversify(
        self,
        tfidf_kw: List[Tuple[str, float]],
        embedrank_kw: List[Tuple[str, float]],
        top_n: int
    ) -> List[str]:

        tfidf_dict = dict(tfidf_kw)
        embedrank_dict = dict(embedrank_kw)

        all_terms = set(tfidf_dict.keys()) | set(embedrank_dict.keys())

        combined_scores = {}
        for term in all_terms:
            tfidf_score = tfidf_dict.get(term, 0)
            embedrank_score = embedrank_dict.get(term, 0)

            max_tfidf = max(tfidf_dict.values()) if tfidf_dict else 1.0
            max_embedrank = max(embedrank_dict.values()) if embedrank_dict else 1.0

            tfidf_norm = tfidf_score / max_tfidf
            embedrank_norm = embedrank_score / max_embedrank

            combined_scores[term] = 0.5 * tfidf_norm + 0.5 * embedrank_norm

        sorted_terms = sorted(combined_scores.items(), key=lambda x: x[1], reverse=True)

        selected = []
        term_embeddings = {}

        for term, score in sorted_terms:
            if len(selected) >= top_n:
                break

            if len(selected) == 0:
                selected.append(term)
                term_embeddings[term] = self.embedding_model.encode([term])[0]
                continue

            term_emb = self.embedding_model.encode([term])[0]

            max_sim = 0
            for sel_term in selected:
                sim = float(cosine_similarity([term_emb], [term_embeddings[sel_term]])[0][0])
                max_sim = max(max_sim, sim)

            if max_sim < 0.70:
                selected.append(term)
                term_embeddings[term] = term_emb

        return selected

    def _calculate_confidence(
        self,
        final_keywords: List[str],
        tfidf_kw: List[Tuple[str, float]],
        embedrank_kw: List[Tuple[str, float]],
        document_text: str,
        graph: nx.Graph
    ) -> Dict[str, float]:

        if not final_keywords:
            return {
                'overall': 0.0,
                'score_distribution': 0.0,
                'document_coverage': 0.0,
                'term_specificity': 0.0,
                'graph_coherence': 0.0
            }

        tfidf_dict = dict(tfidf_kw)
        selected_scores = [tfidf_dict.get(kw, 0) for kw in final_keywords]

        if len(selected_scores) >= 2:
            score_gap = (selected_scores[0] - selected_scores[-1]) / (selected_scores[0] + 1e-6)
            distribution_score = min(1.0, score_gap * 2)
        else:
            distribution_score = 0.5

        doc_lower = document_text.lower()
        found_count = sum(1 for kw in final_keywords if kw in doc_lower)
        coverage_score = found_count / len(final_keywords)

        avg_length = np.mean([len(kw) for kw in final_keywords])
        length_score = min(1.0, avg_length / 12.0)

        domain_count = sum(1 for kw in final_keywords
                            if any(dt in kw for dt in self.domain_terms))
        domain_score = domain_count / len(final_keywords)

        specificity_score = 0.5 * length_score + 0.5 * domain_score

        if graph and len(graph.nodes()) > 1:
            density = nx.density(graph)
            coherence_score = min(1.0, density * 5)
        else:
            coherence_score = 0.5

        overall = (
            0.20 * distribution_score +
            0.40 * coverage_score +
            0.20 * specificity_score +
            0.20 * coherence_score
        )

        return {
            'overall': round(float(overall), 3),
            'score_distribution': round(float(distribution_score), 3),
            'document_coverage': round(float(coverage_score), 3),
            'term_specificity': round(float(specificity_score), 3),
            'graph_coherence': round(float(coherence_score), 3)
        }

    def _preprocess(self, text: str) -> str:
        text = text.lower()
        text = re.sub(r'[^\w\sàèéìòù]', ' ', text)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()

    def _load_stopwords(self) -> Set[str]:
        return {
            'il', 'lo', 'la', 'i', 'gli', 'le', 'un', 'uno', 'una',
            'dei', 'degli', 'delle', 'della', 'dello', 'nell', 'nella', 'nelle', 'nei',
            'di', 'a', 'da', 'in', 'con', 'su', 'per', 'tra', 'fra', 'nel', 'al', 'ai', 'dal', 'dai',
            'come', 'più', 'anche', 'essere', 'avere', 'fare', 'dire', 'stato', 'stata', 'stati', 'state',
            'questo', 'quello', 'stesso', 'altro', 'molto', 'tutto', 'ogni', 'tale', 'quale',
            'quando', 'dove', 'che', 'chi', 'cui', 'cosa', 'quanto', 'anni', 'anno',
            'documento', 'presente', 'seguente', 'generale', 'utilizzo', 'attività',
            'gruppo', 'parte', 'caso', 'modo', 'tutti', 'altre', 'altri', 'altra', 'prima', 'dopo',
            'misure', 'gestione', 'controllo', 'procedure', 'processo', 'sistema',
            'deve', 'devono', 'può', 'possono', 'viene', 'vengono', 'fatto', 'fatta',
            'scheda', 'schede', 'limite', 'limiti', 'dati', 'dato', 'uso', 'dell', 'degli'
        }

    def _save_graph(self, G: nx.Graph, scores: Dict[str, float],
                     output_path: Path, doc_title: str):
        try:
            import matplotlib
            matplotlib.use('Agg')  # Backend non-interattivo per HPC
            import matplotlib.pyplot as plt

            top_nodes = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:25]
            top_node_names = [node for node, _ in top_nodes]

            G_sub = G.subgraph(top_node_names)
            pos = nx.spring_layout(G_sub, k=0.7, iterations=50)

            plt.figure(figsize=(14, 10))

            max_score = max(scores.values()) if scores else 1.0
            node_sizes = [scores.get(node, 0) / max_score * 50000 for node in G_sub.nodes()]
            node_colors = [scores.get(node, 0) for node in G_sub.nodes()]

            nx.draw_networkx_nodes(G_sub, pos, node_size=node_sizes, node_color=node_colors,
                                   cmap=plt.cm.Blues, alpha=0.9, edgecolors='black', linewidths=1.5)

            nx.draw_networkx_edges(G_sub, pos, alpha=0.25, width=1.0)
            nx.draw_networkx_labels(G_sub, pos, font_size=9, font_weight='bold', font_color='darkblue')

            plt.title(f"EmbedRank: {doc_title[:40]}", fontsize=14)
            plt.axis('off')
            plt.tight_layout()

            safe_title = re.sub(r'[^\w\-_]', '_', doc_title[:40])
            graph_file = output_path.parent / f"EmbedRank_{safe_title}.png"
            plt.savefig(graph_file, dpi=150, bbox_inches='tight')
            plt.close()

        except Exception as e:
            pass  # Silenzioso in caso di errore grafico

# ============================================================================
# GENERIC THEME EXTRACTOR
# ============================================================================

class GenericThemeExtractor:
    def __init__(self, embedding_model: SentenceTransformer):
        self.embedding_model = embedding_model

    def extract_themes(
        self,
        keywords: List[str],
        laws: List[str],
        document_text: str
    ) -> List[str]:

        if len(keywords) < 3:
            themes = [kw.capitalize() for kw in keywords[:3]]
            if laws:
                themes.append("Normativa")
            return themes

        embeddings = self.embedding_model.encode(keywords)
        n_clusters = min(4, max(2, len(keywords) // 3))

        try:
            clustering = AgglomerativeClustering(
                n_clusters=n_clusters,
                metric='cosine',
                linkage='average'
            )
            labels = clustering.fit_predict(embeddings)
        except:
            return [kw.capitalize() for kw in keywords[:4]]

        themes = []
        clusters = defaultdict(list)
        for i, label in enumerate(labels):
            clusters[label].append(keywords[i])

        for cluster_kw in clusters.values():
            if len(cluster_kw) == 1:
                themes.append(cluster_kw[0].capitalize())
            elif len(cluster_kw) == 2:
                themes.append(f"{cluster_kw[0].capitalize()} e {cluster_kw[1]}")
            else:
                cluster_embs = self.embedding_model.encode(cluster_kw)
                centroid = np.mean(cluster_embs, axis=0)

                distances = [
                    (kw, float(cosine_similarity([emb], [centroid])[0][0]))
                    for kw, emb in zip(cluster_kw, cluster_embs)
                ]
                distances.sort(key=lambda x: x[1], reverse=True)

                top2 = distances[:2]
                themes.append(f"{top2[0][0].capitalize()} e {top2[1][0]}")

        if laws and len(laws) >= 2:
            if not any("normativ" in t.lower() for t in themes):
                themes.append("Normativa")

        return themes[:4]

# ============================================================================
# CATEGORY CLASSIFIER
# ============================================================================

class DomainAwareCategoryClassifier:
    def __init__(self, embedding_model: SentenceTransformer, valid_categories: List[str],
                 category_terms: Dict[str, List[str]]):
        self.embedding_model = embedding_model
        self.valid_categories = valid_categories
        self.category_terms = category_terms
        self.category_embeddings = embedding_model.encode(valid_categories)

    def classify(self, keywords: List[str], themes: List[str], laws: List[str]) -> str:
        all_text = ' '.join(keywords + themes).lower()

        domain_scores = {}
        for category, terms in self.category_terms.items():
            matches = sum(1 for term in terms if term in all_text)
            domain_scores[category] = matches / max(len(terms), 1)

        for category in self.valid_categories:
            if category not in domain_scores:
                cat_words = set(category.lower().split())
                text_words = set(all_text.split())
                overlap = len(cat_words & text_words)
                domain_scores[category] = overlap / max(len(cat_words), 1)

        if "Normativa e adempimenti" in domain_scores:
            specific_categories = [cat for cat in domain_scores.keys() if cat != "Normativa e adempimenti"]
            max_specific_score = max([domain_scores[cat] for cat in specific_categories], default=0)

            if max_specific_score > 0.15:
                domain_scores["Normativa e adempimenti"] *= 0.3

        top_candidates = sorted(domain_scores.items(), key=lambda x: x[1], reverse=True)[:5]

        description = f"""Keywords: {', '.join(keywords[:10])}.
Temi: {', '.join(themes[:3])}.
Leggi: {', '.join(laws[:3]) if laws else 'Generiche'}."""

        desc_emb = self.embedding_model.encode([description])

        best_category = None
        best_score = 0

        for category, domain_score in top_candidates:
            cat_idx = self.valid_categories.index(category)
            sem_score = float(cosine_similarity(desc_emb, [self.category_embeddings[cat_idx]])[0][0])

            combined_score = 0.7 * domain_score + 0.3 * sem_score

            if combined_score > best_score:
                best_score = combined_score
                best_category = category

        if best_score < Config.CATEGORY_THRESHOLD:
            return "Altro"

        return best_category

# ============================================================================
# PROFESSION EXTRACTOR
# ============================================================================

class ImprovedProfessionExtractor:
    def __init__(self, embedding_model: SentenceTransformer, known_professions: List[str],
                 blacklist: Set[str]):
        self.embedding_model = embedding_model
        self.known_professions = known_professions
        self.blacklist = blacklist
        self.profession_embeddings = embedding_model.encode(known_professions)

    def extract_professions(
        self,
        document_text: str,
        keywords: List[str],
        themes: List[str],
        category: str,
        top_k: int = 3,
        threshold: float = 0.55
    ) -> List[str]:

        doc_desc = f"""Settore: {category}.
Parole chiave: {', '.join(keywords[:8])}.
Temi: {', '.join(themes[:3])}.
Contenuto: {document_text[:1500]}"""

        doc_emb = self.embedding_model.encode([doc_desc])
        similarities = cosine_similarity(doc_emb, self.profession_embeddings)[0]

        ranked = sorted(
            zip(self.known_professions, similarities),
            key=lambda x: x[1],
            reverse=True
        )

        selected = []
        for prof, score in ranked:
            if prof in self.blacklist:
                continue
            if score >= threshold:
                selected.append(prof)
            if len(selected) >= top_k:
                break

        if not selected:
            for prof, score in ranked:
                if prof not in self.blacklist and score > 0.40:
                    selected = [prof]
                    break

        return selected

# ============================================================================
# SUMMARY GENERATOR
# ============================================================================

class ReliableSummaryGenerator:
    def __init__(self, embedding_model: SentenceTransformer):
        self.embedding_model = embedding_model

    def generate_with_confidence(
        self,
        document_text: str,
        keywords: List[str],
        laws: List[str],
        category: str,
        themes: List[str]
    ) -> Tuple[str, Dict[str, float]]:

        summary = self._create_structured_summary(keywords, laws, category, themes, document_text)
        confidence = self._calculate_confidence(summary, document_text, keywords, laws)

        return summary, confidence

    def _create_structured_summary(
        self,
        keywords: List[str],
        laws: List[str],
        category: str,
        themes: List[str],
        document_text: str
    ) -> str:

        top_keywords = keywords[:min(4, len(keywords))]

        if themes and len(themes) > 0:
            main_theme = themes[0].lower()
            intro = f"Documento tecnico che tratta {main_theme}"
        else:
            intro = f"Documento nel settore {category.lower()}"

        if len(top_keywords) >= 3:
            kw_part = f"con focus su {top_keywords[0]}, {top_keywords[1]} e {top_keywords[2]}"
        elif len(top_keywords) == 2:
            kw_part = f"con focus su {top_keywords[0]} e {top_keywords[1]}"
        elif len(top_keywords) == 1:
            kw_part = f"relativo a {top_keywords[0]}"
        else:
            kw_part = ""

        if laws and len(laws) <= 3:
            law_part = f"Riferimenti normativi: {', '.join(laws)}"
        elif laws and len(laws) > 3:
            law_part = f"Principali normative: {laws[0]}, {laws[1]}"
        else:
            law_part = ""

        summary_parts = [intro]
        if kw_part:
            summary_parts.append(kw_part)

        if len(summary_parts) == 2:
            summary = f"{summary_parts[0]} {summary_parts[1]}"
        else:
            summary = summary_parts[0]

        if law_part:
            summary = f"{summary}. {law_part}"

        if not summary.endswith('.'):
            summary += '.'

        summary = summary[0].upper() + summary[1:]

        return summary

    def _calculate_confidence(
        self,
        summary: str,
        document_text: str,
        keywords: List[str],
        laws: List[str]
    ) -> Dict[str, float]:

        try:
            sum_emb = self.embedding_model.encode([summary])[0]
            doc_emb = self.embedding_model.encode([document_text[:4500]])[0]
            grounding = float(cosine_similarity([sum_emb], [doc_emb])[0][0])
        except:
            grounding = 0.5

        summary_lower = summary.lower()
        kw_mentioned = sum(1 for kw in keywords[:8] if kw.lower() in summary_lower)
        kw_coverage = kw_mentioned / min(len(keywords), 8)

        if laws:
            laws_mentioned = 0
            for law in laws[:4]:
                law_parts = re.findall(r'\d+', law)
                if any(part in summary for part in law_parts):
                    laws_mentioned += 1

            factuality = laws_mentioned / min(len(laws), 4)
        else:
            factuality = 0.7

        overall = 0.50 * grounding + 0.35 * kw_coverage + 0.15 * factuality

        return {
            'overall': round(overall, 3),
            'grounding': round(grounding, 3),
            'keyword_coverage': round(kw_coverage, 3),
            'factuality': round(factuality, 3)
        }

# ============================================================================
# GLOBAL CONFIDENCE
# ============================================================================

class GlobalConfidenceCalculator:
    def calculate(
        self,
        keyword_confidence: Dict[str, float],
        law_confidence: Dict[str, float],
        summary_confidence: Dict[str, float]
    ) -> Dict[str, Any]:

        kw_score = keyword_confidence.get('overall', 0.0)
        law_score = law_confidence.get('overall', 0.0)
        sum_score = summary_confidence.get('overall', 0.0)

        overall = 0.45 * kw_score + 0.30 * law_score + 0.25 * sum_score

        review_reasons = []

        if overall >= 0.68:
            level = "HIGH"
            needs_review = False
        elif overall >= 0.52:
            level = "MEDIUM"
            needs_review = True
            review_reasons.append("Confidence medio: verificare campione")
        else:
            level = "LOW"
            needs_review = True
            review_reasons.append("Confidence basso: revisione manuale richiesta")

        if kw_score < 0.48:
            review_reasons.append(f"Keywords confidence basso ({kw_score:.2f})")
        if law_score < 0.43:
            review_reasons.append(f"Laws confidence basso ({law_score:.2f})")
        if sum_score < 0.48:
            review_reasons.append(f"Summary grounding basso ({sum_score:.2f})")

        return {
            'overall_score': round(overall, 3),
            'confidence_level': level,
            'needs_review': needs_review,
            'components': {
                'keywords': round(kw_score, 3),
                'laws': round(law_score, 3),
                'summary': round(sum_score, 3)
            },
            'detailed_components': {
                'keywords': keyword_confidence,
                'laws': law_confidence,
                'summary': summary_confidence
            },
            'review_reasons': review_reasons
        }

# ============================================================================
# UTILITIES
# ============================================================================

def extract_full_document_text(document_data: Dict[str, Any]) -> str:
    chunks = []
    abstract = document_data.get('web_metadata', {}).get('abstract', '')
    if abstract:
        chunks.append(f"ABSTRACT:\n{abstract}\n")

    content = document_data.get('document_content', {})
    if content.get('plain_text'):
        chunks.append(content['plain_text'])
    elif content.get('markdown_content'):
        chunks.append(content['markdown_content'])

    return '\n\n'.join(chunks)

def setup_logging_hpc(log_dir: Path):
    log_dir.mkdir(exist_ok=True, parents=True)
    log_file = log_dir / f"enrichment_hpc_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(message)s',
        handlers=[logging.FileHandler(log_file), logging.StreamHandler()]
    )
    return logging.getLogger(__name__), log_file

# ============================================================================
# DOCUMENT ENRICHMENT
# ============================================================================

def enrich_document_final(
    document_data: Dict[str, Any],
    law_extractor: LawExtractor,
    keyword_extractor: DomainAwareTFIDFExtractor,
    theme_extractor: GenericThemeExtractor,
    profession_extractor: ImprovedProfessionExtractor,
    summary_generator: ReliableSummaryGenerator,
    category_classifier: DomainAwareCategoryClassifier,
    confidence_calculator: GlobalConfidenceCalculator,
    logger: logging.Logger,
    save_graph: bool = True
) -> Optional[Dict[str, Any]]:

    doc_title = document_data.get('web_metadata', {}).get('title', 'N/A')

    try:
        full_text = extract_full_document_text(document_data)

        if len(full_text) < Config.MIN_TEXT_LENGTH:
            logger.warning(f"Testo troppo corto per: {doc_title[:60]}")
            return None

        laws, law_confidence = law_extractor.extract_with_confidence(full_text)

        graph_path = Config.GRAPH_DIR / "temp.png" if save_graph else None
        keywords, kw_metadata, G = keyword_extractor.extract_keywords_with_confidence(
            full_text, top_n=8, save_graph=save_graph,
            graph_path=graph_path, doc_title=doc_title
        )

        themes = theme_extractor.extract_themes(keywords, laws, full_text)
        categoria = category_classifier.classify(keywords, themes, laws)
        sintesi, summary_confidence = summary_generator.generate_with_confidence(
            full_text, keywords, laws, categoria, themes
        )
        professioni = profession_extractor.extract_professions(
            full_text, keywords, themes, categoria, top_k=3, threshold=Config.PROFESSION_THRESHOLD
        )

        global_confidence = confidence_calculator.calculate(
            kw_metadata['confidence'],
            law_confidence,
            summary_confidence
        )

        logger.info(f"✓ {doc_title[:60]} | Confidence: {global_confidence['overall_score']:.3f} ({global_confidence['confidence_level']})")

        metadata = {
            'sintesi': sintesi,
            'categoria_principale': categoria,
            'articoli_legge': laws,
            'categorie_professionali': professioni,
            'parole_chiave': keywords,
            'temi_principali': themes,
            'confidence': global_confidence,
            'extraction_details': kw_metadata,
            'extraction_methods': {
                'keywords': 'TF-IDF Domain-Aware + EmbedRank',
                'themes': 'Semantic Clustering',
                'category': 'Domain-Aware Hierarchical',
                'laws': 'Regex Pattern Matching',
                'summary': 'Structured Fallback',
                'professions': 'BERT Semantic + Blacklist',
                'confidence': 'Multi-component'
            },
            'generated_at': datetime.now().isoformat(),
            'version': 'HPC_v1.0_EmbeddingGemma'
        }

        enriched_doc = document_data.copy()
        enriched_doc['semantic_metadata'] = metadata

        return enriched_doc

    except Exception as e:
        logger.error(f"ERROR processing {doc_title}: {e}")
        traceback.print_exc()
        return None

# ============================================================================
# BATCH PROCESSING
# ============================================================================

def batch_process_all_hpc():
    print("\n" + "="*80)
    print("BATCH PROCESSING - HPC INAIL Documents")
    print("="*80 + "\n")

    if not Config.setup():
        print("❌ Setup failed")
        return

    logger, log_file = setup_logging_hpc(Config.LOG_DIR)
    logger.info("="*80)
    logger.info("INIZIO BATCH PROCESSING HPC")
    logger.info("="*80)

    print("\n[Setup] Caricamento modello embedding...")
    embedding_model = load_embedding_model_hpc()
    if not embedding_model:
        print("❌ Errore caricamento modello embedding")
        return
    print("✓ Modello pronto\n")

    # Inizializzazione componenti
    law_extractor = LawExtractor()
    keyword_extractor = DomainAwareTFIDFExtractor(embedding_model, Config.DOMAIN_TERMS)
    theme_extractor = GenericThemeExtractor(embedding_model)
    profession_extractor = ImprovedProfessionExtractor(
        embedding_model,
        Config.KNOWN_PROFESSIONS,
        Config.PROFESSION_BLACKLIST
    )
    summary_generator = ReliableSummaryGenerator(embedding_model)
    category_classifier = DomainAwareCategoryClassifier(
        embedding_model,
        Config.DOCUMENT_CATEGORIES,
        Config.CATEGORY_TERMS
    )
    confidence_calculator = GlobalConfidenceCalculator()

    # Get all JSON files
    json_files = sorted([f for f in Config.JSON_DIR.glob("*.json")
                         if not f.name.startswith('vector_db')])

    logger.info(f"Trovati {len(json_files)} documenti da processare")
    print(f"Found {len(json_files)} documents\n")

    success_count = 0
    fail_count = 0
    confidence_stats = {'HIGH': 0, 'MEDIUM': 0, 'LOW': 0}

    for i, json_file in enumerate(json_files, 1):
        if i % 10 == 0:
            print(f"Progress: {i}/{len(json_files)} ({i/len(json_files)*100:.1f}%)")

        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                doc = json.load(f)

            enriched = enrich_document_final(
                doc, law_extractor, keyword_extractor, theme_extractor,
                profession_extractor, summary_generator, category_classifier,
                confidence_calculator, logger, save_graph=Config.SAVE_ALL_GRAPHS
            )

            if enriched:
                output_path = Config.ENRICHED_DIR / json_file.name
                with open(output_path, 'w', encoding='utf-8') as f:
                    json.dump(enriched, f, ensure_ascii=False, indent=2)

                conf_level = enriched['semantic_metadata']['confidence']['confidence_level']
                confidence_stats[conf_level] += 1
                success_count += 1
            else:
                fail_count += 1

        except Exception as e:
            fail_count += 1
            logger.error(f"FATAL ERROR processing {json_file.name}: {e}")

    logger.info("="*80)
    logger.info("BATCH PROCESSING COMPLETATO")
    logger.info("="*80)
    logger.info(f"Success: {success_count}")
    logger.info(f"Failed: {fail_count}")
    logger.info(f"Total: {len(json_files)}")
    logger.info(f"Confidence Distribution:")
    total_success = max(success_count, 1)
    logger.info(f"  HIGH:   {confidence_stats['HIGH']} ({confidence_stats['HIGH']/total_success*100:.1f}%)")
    logger.info(f"  MEDIUM: {confidence_stats['MEDIUM']} ({confidence_stats['MEDIUM']/total_success*100:.1f}%)")
    logger.info(f"  LOW:    {confidence_stats['LOW']} ({confidence_stats['LOW']/total_success*100:.1f}%)")

    print(f"\n{'='*80}")
    print(f"BATCH COMPLETE")
    print(f"{'='*80}")
    print(f"Success: {success_count}")
    print(f"Failed: {fail_count}")
    print(f"Total: {len(json_files)}")
    print(f"\nConfidence Distribution:")
    print(f"  HIGH:   {confidence_stats['HIGH']} ({confidence_stats['HIGH']/total_success*100:.1f}%)")
    print(f"  MEDIUM: {confidence_stats['MEDIUM']} ({confidence_stats['MEDIUM']/total_success*100:.1f}%)")
    print(f"  LOW:    {confidence_stats['LOW']} ({confidence_stats['LOW']/total_success*100:.1f}%)")
    print(f"\n✓ Log salvato: {log_file}")
    print(f"✓ Enriched JSON in: {Config.ENRICHED_DIR}")
    if Config.SAVE_ALL_GRAPHS:
        print(f"✓ Grafi salvati in: {Config.GRAPH_DIR}")
    print(f"{'='*80}\n")

# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    batch_process_all_hpc()